/**
 * useWorkoutTTS — Voice coaching hook for the Workout Player
 *
 * Audio pipeline:
 *   1. Pre-generated movement voice clips (OpenAI TTS, stored at voiceUrl)
 *   2. Static platform cues (Firebase Storage MP3s)
 *
 * Web Speech / expo-speech are intentionally NOT part of the normal audible
 * path. When a voiceUrl is missing or fails to load, we log the gap and stay
 * silent rather than speaking the text via device speech — the robotic device
 * voice sounded cheap compared to the OpenAI clips and was overlapping the
 * static cues (e.g. "Next up" MP3 + "Next up, {movement}" device speech).
 *
 * Sequencing model (queue-based, not timer-based):
 *   Every cue and voice clip is pushed onto a single FIFO queue and played
 *   one at a time. Each clip's natural `ended` event (plus a small fixed
 *   QUEUE_GAP_MS gap) triggers the next dequeue. This replaces the old
 *   setTimeout ladder (1100ms → 1800ms) that was guessing at clip lengths —
 *   under the old approach, a long movement-name voice clip would overlap
 *   with the subsequent "next up" or rest countdown because the next cue
 *   fired on a fixed timer instead of waiting for the previous audio to end.
 *
 *   Expected sequence when work → rest:
 *     [countdown_3 (work last 3s)] → [rest (work end)] →
 *     [next_up cue (rest start)] → [next movement's OpenAI voiceUrl]
 *   Expected sequence when rest → work:
 *     [countdown_3 (rest last 3s)] → [go (rest end)]
 *   Expected sequence when swap-sides L → swap → R (window ≥ 1):
 *     [countdown_3 (work-L last 3s)] → [switch_sides (swap entry)] →
 *     [(visual countdown only)] → [go (swap end)]
 *   Expected sequence when swap-sides L → R, window === 0 (no swap phase):
 *     [countdown_3 (work-L last 3s)] → [other_side (work-L end)] →
 *     work-R → [countdown_3 (work-R last 3s)] → [rest/next chain]
 *
 *   ALL combined Voicemaker phrase clips were dropped. Every clip we used to
 *   pre-warm (per-movement workRestNext / workNext / nextUp, shared
 *   workSwapOtherSide, swap-window swap-entry phrases, and the shared
 *   rest→go "3, 2, 1. Go." clip) had the same failure surface: when the clip
 *   stalled or failed to load, the suppression flag set at enqueue time
 *   silenced the static fallback, leaving the transition dead-air. The
 *   audio pipeline is now static MP3 cues + per-movement OpenAI voiceUrl
 *   clips only — each clip succeeds or fails on its own with no shared
 *   point of failure.
 *
 *   Movement-name fallback: the rest screen normally enqueues `next_up` +
 *   the next movement's voiceUrl. When voiceUrl is missing or empty at rest
 *   time (legacy movement not yet voice-generated, mid-regeneration after
 *   a rename), the work-start branch enqueues voiceUrl as a fallback so the
 *   member still hears the name once the movement begins. The
 *   restAnnouncedVoiceUrlForIndexRef tracks whether rest actually queued a
 *   non-empty voiceUrl for the upcoming index so the work-start branch
 *   knows whether to fire the fallback.
 *
 *   Invalidation rules:
 *     • Skip:  stopAllAudio() bumps runIdRef, flushes queue, stops current audio.
 *     • Pause: flushes queue + stops current audio (runIdRef NOT bumped so that
 *              anything already spoken stays tracked via lastSpokenRef).
 *     • Mute:  flushes queue; future enqueues are silently dropped.
 *     • Phase change: no forced flush — queued items from the previous phase
 *       (e.g. "rest" cue enqueued at end of work) are allowed to complete
 *       naturally. The late-voiceUrl watcher gates on `timeLeft > 3.5` so we
 *       never enqueue a long voice clip into the rest→work countdown window.
 *
 * End-of-workout audio rule (single source of truth):
 *   - If the workout has an Outro block, the long completion clip
 *     (`workout_complete_long`) plays once when the outro phase begins, and
 *     the per-exercise countdown does NOT also fire `workout_complete` for
 *     the last exercise (the outro itself is the last step).
 *   - If there is no Outro block, the short `workout_complete` MP3 plays
 *     once when the last exercise's timer hits 0. The arpeggio tone in
 *     audioCues.ts is no longer used for end-of-workout to avoid stacking.
 */
import { useEffect, useRef, useCallback, useState } from 'react';
import * as Speech from 'expo-speech';
import { Platform } from 'react-native';
import { getFunctions, httpsCallable } from 'firebase/functions';
import type { StepType } from './useWorkoutFlatten';
import { normalizeTtsText, hashTtsText } from '../utils/normalizeTtsText';
import {
  TTS_PROVIDER,
  TTS_VOICE_ID,
  TTS_VOICE_EFFECT,
  TTS_VOICE_SLUG,
  TTS_ENGINE,
  TTS_LANGUAGE_CODE,
  TTS_SAMPLE_RATE,
  TTS_MASTER_SPEED,
  TTS_MASTER_PITCH,
  TTS_MASTER_VOLUME,
  TTS_FILE_STORE_HOURS,
} from '../utils/ttsProviderConfig';

// ── Static cue URL map ──────────────────────────────────────────────
// Static cues are pre-generated by scripts/regenerate-platform-cues-voicemaker.js
// (Voicemaker ai3-Aria, friendly effect) and uploaded to a provider-namespaced
// path. Re-run the script to refresh cue audio after editing the phrase text
// or the break-tag pacing in that file. The CUE_PROVIDER_SLUG must match the
// PROVIDER_SLUG constant in the regen script.
const BASE_URL =
  'https://firebasestorage.googleapis.com/v0/b/goarrive.firebasestorage.app/o/voice_cache%2Fplatform%2F';
const CUE_PROVIDER_SLUG = 'voicemaker-ai3-aria-friendly';
const CUE_URL = (name: string) => `${BASE_URL}${CUE_PROVIDER_SLUG}-${name}.mp3?alt=media`;

const CUES = {
  countdown_3: CUE_URL('countdown_3'),
  countdown_3_rest: CUE_URL('countdown_3_rest'),
  countdown_4: CUE_URL('countdown_4'),
  countdown_5: CUE_URL('countdown_5'),
  countdown_10: CUE_URL('countdown_10'),
  five_seconds: CUE_URL('five_seconds'),
  ten_seconds: CUE_URL('ten_seconds'),
  go: CUE_URL('go'),
  begin: CUE_URL('begin'),
  rest: CUE_URL('rest'),
  rest_now: CUE_URL('rest_now'),
  halfway: CUE_URL('halfway'),
  workout_complete: CUE_URL('workout_complete'),
  workout_complete_long: CUE_URL('workout_complete_long'),
  workout_starting: CUE_URL('workout_starting'),
  start_now: CUE_URL('start_now'),
  next_up: CUE_URL('next_up'),
  get_ready: CUE_URL('get_ready'),
  switch_sides: CUE_URL('switch_sides'),
  other_side: CUE_URL('other_side'),
  water_break: CUE_URL('water_break'),
  heres_whats_coming_up: CUE_URL('heres_whats_coming_up'),
  warm_up: CUE_URL('warm_up'),
  cool_down: CUE_URL('cool_down'),
  stretch: CUE_URL('stretch'),
  shake_it_out: CUE_URL('shake_it_out'),
  lets_get_started: CUE_URL('lets_get_started'),
  lets_go: CUE_URL('lets_go'),
  breathe: CUE_URL('breathe'),
  take_a_breath: CUE_URL('take_a_breath'),
  you_got_this: CUE_URL('you_got_this'),
  keep_pushing: CUE_URL('keep_pushing'),
  almost_there: CUE_URL('almost_there'),
  last_round: CUE_URL('last_round'),
  last_set: CUE_URL('last_set'),
  final_rep: CUE_URL('final_rep'),
  one_more: CUE_URL('one_more'),
  push_through: CUE_URL('push_through'),
  dig_deep: CUE_URL('dig_deep'),
  dont_stop: CUE_URL('dont_stop'),
  stay_strong: CUE_URL('stay_strong'),
} as const;

type CueKey = keyof typeof CUES;

// ── Audio pool for pre-loaded cues AND voice clips ────────────────────
// Keyed: cue items use `cue:<key>`, voice items use `voice:<url>`. Pooling
// voice clips matters as much as pooling cues — iOS Safari throttles or
// silently fails new HTMLAudioElement creations after several elements are
// alive on the page. The combined transition phrase clips are reused every
// round (per movement name + the shared restGo); without pooling, each round
// allocated a fresh element until Safari refused to actually start playback,
// the `ended` event never fired, and the queue deadlocked while still
// accepting enqueues. Pool size in a workout is bounded by unique movement
// count + the static cue keys, so unbounded growth isn't a concern.
const audioPool: Record<string, HTMLAudioElement> = {};

function poolKeyForCue(key: CueKey): string {
  return `cue:${key}`;
}
function poolKeyForVoice(url: string): string {
  return `voice:${url}`;
}

function preloadCue(key: CueKey): void {
  if (Platform.OS !== 'web') return;
  if (typeof window === 'undefined') return;
  const poolKey = poolKeyForCue(key);
  if (audioPool[poolKey]) return;
  try {
    const audio = new (window as any).Audio(CUES[key]);
    audio.preload = 'auto';
    audioPool[poolKey] = audio;
  } catch {
    // Audio API unavailable
  }
}

// Pre-load the most commonly used cues immediately. `go` is critical: without
// it preloaded, the first rest's "Go" cue has to fetch over network on first
// use and can arrive after the work phase has already started, making the
// first rest-to-work transition silent while later rests (with `go` cached in
// audioPool) play cleanly.
const PRIORITY_CUES: CueKey[] = [
  'countdown_3', 'countdown_3_rest', 'rest', 'go', 'halfway',
  'workout_complete', 'next_up', 'you_got_this', 'keep_pushing',
  'almost_there', 'workout_starting', 'lets_get_started',
];
if (Platform.OS === 'web' && typeof window !== 'undefined') {
  // Defer preloading slightly to not block initial render
  setTimeout(() => PRIORITY_CUES.forEach(preloadCue), 2000);
}

// Default swap window length when the movement's swapWindowSec field is
// missing or out of range. Matches DEFAULT_SWAP_WINDOW_SEC in useWorkoutTimer
// so the TTS phrase-selection logic and the timer agree on what window
// length actually plays.
const DEFAULT_SWAP_WINDOW_SEC = 5;
function swapWindowSeconds(mov: any): number {
  const raw = mov?.swapWindowSec;
  if (typeof raw === 'number' && raw >= 0 && raw <= 15) return raw;
  return DEFAULT_SWAP_WINDOW_SEC;
}

// Natural gap between consecutive clips. Not a guess at clip length — the
// queue already waits for the previous clip's `ended` event before starting
// this gap. Tightened from 220ms after the rest flow consolidated to one
// "Next up, {name}." phrase clip — the long silence between separate
// "Next up" and movement-name clips was the main offender, and 220ms
// between [rest]→[combined phrase] still felt awkward. 90ms reads as a
// natural sentence boundary without bleeding clips into each other.
export const QUEUE_GAP_MS = 90;

// Pure helpers exported for testing.
export type QueueItemKind = 'cue' | 'voice';

// Returns the gap (ms) to insert between two consecutive audio queue items.
// cue→voice = 0 so "next up, [movement]" plays as one continuous statement.
export function calcQueueGapMs(
  currentKind: QueueItemKind,
  nextItemKind: QueueItemKind | null,
): number {
  if (currentKind === 'cue' && nextItemKind === 'voice') return 0;
  return QUEUE_GAP_MS;
}

// Drops queue items whose runId doesn't match currentRunId.
export function filterStaleQueueItems<T extends { runId: number }>(
  items: T[],
  currentRunId: number,
): T[] {
  return items.filter((item) => item.runId === currentRunId);
}

// ── Types ────────────────────────────────────────────────────────────
type Phase = 'ready' | 'work' | 'rest' | 'swap' | 'complete'
  | 'intro' | 'outro' | 'demo' | 'transition' | 'waterBreak' | 'grabEquipment'
  | 'followAlongVideo';

type QueueItem =
  | { kind: 'cue'; key: CueKey; context: string; runId: number }
  | { kind: 'voice'; url: string; context: string; runId: number };

interface UseWorkoutTTSOptions {
  phase: Phase;
  current: {
    name: string;
    stepType?: StepType;
    instructionText?: string;
    demoMovements?: { name: string }[];
    [key: string]: any;
  } | null;
  next: { name: string; [key: string]: any } | null;
  isMuted: boolean;
  isPaused: boolean;
  ttsDisabled?: boolean;
  currentIndex: number;
  total: number;
  timeLeft: number;
  currentDuration: number;
  /**
   * Which side of a swap-sides movement we're on. Used to suppress the
   * end-of-work `rest` cue when work-L ends (the swap-phase effect plays
   * `switch_sides` immediately after), so we don't say "Rest" + "Switch sides"
   * back-to-back.
   */
  swapSide?: 'L' | 'R';
}

export function useWorkoutTTS({
  phase,
  current,
  next,
  isMuted,
  isPaused,
  ttsDisabled = false,
  currentIndex,
  total,
  timeLeft,
  currentDuration,
  swapSide = 'L',
}: UseWorkoutTTSOptions) {
  const lastSpokenRef = useRef<string>('');
  const [isTTSAvailable, setIsTTSAvailable] = useState(true);
  const halfwaySpokenRef = useRef<boolean>(false);
  const countdownSpokenRef = useRef<number>(-1);
  const restCountdownSpokenRef = useRef<number>(-1);
  const welcomeSpokenRef = useRef<boolean>(false);

  // Tracks the currentIndex+1 (upcoming movement index) for which the rest
  // phase successfully enqueued a non-empty voiceUrl. Checked at work-start to
  // decide whether to fire a voiceUrl fallback — if rest's voiceUrl was empty
  // (legacy/regenerating movement), the work branch announces the name then.
  const restAnnouncedVoiceUrlForIndexRef = useRef<number>(-1);
  const lastGoEnqueuedAtRef = useRef<number>(0);
  // Cache for grab-equipment voice URLs: normalized-text-hash → Storage URL (or null on failure)
  const grabEquipVoiceCacheRef = useRef<Record<string, string | null>>({});
  const grabEquipGeneratingRef = useRef<Set<string>>(new Set());
  // Mirror isPaused for synchronous use inside the queue pump callbacks.
  const isPausedRef = useRef(isPaused);
  useEffect(() => { isPausedRef.current = isPaused; }, [isPaused]);

  // ── Audio queue state ───────────────────────────────────────────────
  // One-item-at-a-time FIFO. Every cue and voice clip goes through this
  // queue; nothing plays out-of-band. The queue guarantees:
  //   1. Only one audio element is playing at any moment (no overlap).
  //   2. The next item starts only after the previous one's `ended` event
  //      fires (no cutoffs — we never guess at clip length).
  //   3. Skip / Mute flushes the queue atomically via a runId bump so any
  //      already-enqueued items that have become stale are discarded.
  const queueRef = useRef<QueueItem[]>([]);
  const isPlayingRef = useRef<boolean>(false);
  const currentAudioRef = useRef<HTMLAudioElement | null>(null);
  // Monotonic counter; bumped by stopAllAudio() to invalidate in-flight items.
  const runIdRef = useRef<number>(0);
  // setTimeout handle for the QUEUE_GAP_MS gap between clips — tracked so we
  // can cancel it on flush (otherwise a pending gap-timer would fire pumpQueue
  // just after a flush and start playing whatever arrived next).
  const gapTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const logSpeechSuppressed = useCallback(
    (context: string, text: string) => {
      if (isMuted || ttsDisabled || isPausedRef.current) return;
      console.warn(
        '[useWorkoutTTS] Web Speech suppressed (no OpenAI/MP3 cue available):',
        context,
        { text: text.slice(0, 120) },
      );
    },
    [isMuted, ttsDisabled],
  );

  // Plays the next queued item. Called after each `ended` event + gap, and
  // whenever a new item is enqueued while the queue is idle. Idempotent — if
  // already playing, does nothing. Drops stale items (bumped runId) without
  // playing them.
  const pumpQueue = useCallback(() => {
    if (Platform.OS !== 'web' || typeof window === 'undefined') {
      console.info('[VOICE-AUDIT] pumpQueue skipped — non-web platform');
      return;
    }
    if (isPlayingRef.current) {
      console.info('[VOICE-AUDIT] pumpQueue skipped — isPlayingRef=true', {
        queueLen: queueRef.current.length,
        nextContext: queueRef.current[0]?.context,
      });
      return;
    }
    if (isPausedRef.current || isMuted || ttsDisabled) {
      console.info('[VOICE-AUDIT] pumpQueue skipped — paused/muted/disabled', {
        isPaused: isPausedRef.current, isMuted, ttsDisabled,
        queueLen: queueRef.current.length,
      });
      return;
    }

    // Drop stale items from the head of the queue.
    let droppedStale = 0;
    while (queueRef.current.length > 0 && queueRef.current[0].runId !== runIdRef.current) {
      queueRef.current.shift();
      droppedStale++;
    }
    if (droppedStale > 0) {
      console.info('[VOICE-AUDIT] pumpQueue dropped stale items', { droppedStale });
    }
    if (queueRef.current.length === 0) {
      console.info('[VOICE-AUDIT] pumpQueue idle — queue empty');
      return;
    }

    const queueLenBefore = queueRef.current.length;
    const item = queueRef.current.shift()!;
    const queueLenAfter = queueRef.current.length;
    const url = item.kind === 'cue' ? CUES[item.key] : item.url;
    if (!url) {
      console.warn('[VOICE-AUDIT] pumpQueue dequeued empty url — skipping', {
        context: item.context, queueLenBefore, queueLenAfter,
      });
      if (item.kind === 'voice') logSpeechSuppressed(item.context, '');
      pumpQueue();
      return;
    }

    const poolKey = item.kind === 'cue' ? poolKeyForCue(item.key) : poolKeyForVoice(item.url);
    let audio: HTMLAudioElement;
    let pooledHit = false;
    try {
      const pooled = audioPool[poolKey];
      if (pooled) {
        audio = pooled;
        pooledHit = true;
        try { audio.currentTime = 0; } catch {}
      } else {
        audio = new (window as any).Audio(url);
        audio.preload = 'auto';
        audioPool[poolKey] = audio;
      }
    } catch (err) {
      console.warn('[VOICE-AUDIT] PLAY SETUP THREW', { context: item.context, err });
      pumpQueue();
      return;
    }

    // Use AbortController to remove ended/error/playing listeners on flush so
    // a pooled element can't accumulate stale listeners across rounds (an old
    // listener firing late would mutate isPlayingRef out from under a fresh
    // play and re-pump the queue mid-clip).
    const ac =
      typeof AbortController !== 'undefined' ? new AbortController() : null;
    const listenerOpts: AddEventListenerOptions = ac
      ? { once: true, signal: ac.signal }
      : { once: true };

    isPlayingRef.current = true;
    currentAudioRef.current = audio;
    const myRunId = item.runId;
    let settled = false;
    let started = false;
    let watchdog: ReturnType<typeof setTimeout> | null = null;
    console.info('[VOICE-AUDIT] PLAY ATTEMPT', {
      context: item.context,
      kind: item.kind,
      pooledHit,
      queueLenBefore,
      queueLenAfter,
      isPlayingRef: true,
      readyState: audio.readyState,
    });

    const onDone = (reason: string, detail?: unknown) => {
      if (settled) return;
      settled = true;
      if (watchdog) { clearTimeout(watchdog); watchdog = null; }
      if (ac) {
        try { ac.abort(); } catch {}
      }
      if (reason === 'ended') {
        console.info('[VOICE-AUDIT] PLAY ENDED', { context: item.context, started });
      } else {
        console.warn('[VOICE-AUDIT] PLAY ENDED EARLY', {
          context: item.context, reason, started,
          mediaError: (audio as any).error?.code,
          detail,
        });
      }
      if (currentAudioRef.current === audio) currentAudioRef.current = null;
      isPlayingRef.current = false;
      // If a flush happened (runId bumped) while we were playing, don't pump —
      // the flush already cleared the queue and we should stay quiet until the
      // next enqueue.
      if (myRunId !== runIdRef.current) return;
      if (gapTimerRef.current) clearTimeout(gapTimerRef.current);
      const nextItemKind = queueRef.current[0]?.kind;
      const gapMs = (item.kind === 'cue' && nextItemKind === 'voice') ? 0 : QUEUE_GAP_MS;
      gapTimerRef.current = setTimeout(() => {
        gapTimerRef.current = null;
        pumpQueue();
      }, gapMs);
    };

    audio.addEventListener('ended', () => onDone('ended'), listenerOpts);
    audio.addEventListener(
      'error',
      () => onDone('error', (audio as any).error),
      listenerOpts,
    );
    audio.addEventListener(
      'playing',
      () => {
        started = true;
        console.info('[VOICE-AUDIT] PLAY STARTED', {
          context: item.context,
          duration: audio.duration,
        });
      },
      listenerOpts,
    );

    try {
      const p = audio.play();
      if (p && typeof p.then === 'function') {
        p.then(
          () => {
            console.info('[VOICE-AUDIT] PLAY RESOLVED', {
              context: item.context, paused: audio.paused, started,
            });
          },
          (err: unknown) => onDone('play-rejected', err),
        );
      }
    } catch (err) {
      onDone('play-threw', err);
      return;
    }

    // Watchdog: if play() resolved but the 'playing' event never fires within
    // 5s, the audio element is wedged (iOS Safari can resolve play() without
    // actually starting playback after several elements have been created).
    // Drop the pooled element so the next play creates a fresh one, and pump
    // the next item so the queue doesn't deadlock.
    watchdog = setTimeout(() => {
      if (settled || started) return;
      console.warn('[VOICE-AUDIT] PLAY STALLED — no `playing` event in 5s', {
        context: item.context,
        readyState: audio.readyState,
        networkState: audio.networkState,
        paused: audio.paused,
        currentTime: audio.currentTime,
        mediaError: (audio as any).error?.code,
      });
      // Evict the wedged element from the pool so the next attempt for this
      // URL/cue creates a fresh HTMLAudioElement.
      if (audioPool[poolKey] === audio) {
        try { audio.pause(); } catch {}
        delete audioPool[poolKey];
      }
      onDone('play-stalled');
    }, 5000);
  }, [isMuted, ttsDisabled, logSpeechSuppressed]);

  // ── Queue API ───────────────────────────────────────────────────────
  const enqueueCue = useCallback(
    (key: CueKey, context: string = '') => {
      if (isMuted || ttsDisabled) return;
      if (Platform.OS !== 'web' || typeof window === 'undefined') return;
      queueRef.current.push({ kind: 'cue', key, context, runId: runIdRef.current });
      pumpQueue();
    },
    [isMuted, ttsDisabled, pumpQueue],
  );

  // Enqueue a dynamic voice URL (OpenAI movement clips). Empty URL logs the
  // gap and does not enqueue (nothing would play anyway).
  const enqueueVoice = useCallback(
    (url: string, context: string) => {
      if (isMuted || ttsDisabled) {
        console.warn('[VOICE-AUDIT] enqueueVoice dropped — muted/ttsDisabled', { context, isMuted, ttsDisabled });
        return;
      }
      if (Platform.OS !== 'web' || typeof window === 'undefined') return;
      if (!url) {
        console.warn('[VOICE-AUDIT] enqueueVoice dropped — empty url', { context });
        logSpeechSuppressed(context, '');
        return;
      }
      console.info('[VOICE-AUDIT] enqueueVoice queued', { context, urlPreview: url.slice(0, 80) });
      const poolKey = poolKeyForVoice(url);
      if (!audioPool[poolKey]) {
        try {
          const audio = new (window as any).Audio(url);
          audio.preload = 'auto';
          audioPool[poolKey] = audio;
        } catch {
          // preload failed — pumpQueue will allocate on dequeue
        }
      }
      queueRef.current.push({ kind: 'voice', url, context, runId: runIdRef.current });
      pumpQueue();
    },
    [isMuted, ttsDisabled, logSpeechSuppressed, pumpQueue],
  );

  // Flush everything: bump runId so in-flight play()s drop their post-ended
  // pump, stop the currently playing audio, clear pending items, cancel the
  // inter-clip gap timer. Called from Skip (resetSpoken=true) so the new skip
  // target's cues fire fresh, and from Pause (resetSpoken=false) where we
  // keep track of what was already announced so cues don't double up on
  // resume.
  const stopAllAudio = useCallback((resetSpoken = true) => {
    runIdRef.current += 1;
    queueRef.current.length = 0;
    if (gapTimerRef.current) {
      clearTimeout(gapTimerRef.current);
      gapTimerRef.current = null;
    }
    try {
      if (currentAudioRef.current) {
        currentAudioRef.current.pause();
        try { currentAudioRef.current.currentTime = 0; } catch {}
      }
      if (Platform.OS === 'web' && typeof window !== 'undefined') {
        window.speechSynthesis?.cancel();
      } else {
        Speech.stop();
      }
    } catch {}
    currentAudioRef.current = null;
    isPlayingRef.current = false;
    if (resetSpoken) {
      countdownSpokenRef.current = -1;
      halfwaySpokenRef.current = false;
      restAnnouncedVoiceUrlForIndexRef.current = -1;
    }
  }, []);

  // On web, we always have audio (our own files). On native, check expo-speech.
  useEffect(() => {
    if (Platform.OS === 'web') {
      setIsTTSAvailable(typeof window !== 'undefined');
    } else {
      Speech.getAvailableVoicesAsync()
        .then((voices) => setIsTTSAvailable(voices.length > 0))
        .catch(() => setIsTTSAvailable(false));
    }
  }, []);

  // ── Special block announcements ────────────────────────────────────
  useEffect(() => {
    if (isPaused) return;
    if (!current) return;
    const stepType = current.stepType;

    // Intro block
    if (phase === 'intro' || (phase === 'work' && stepType === 'intro')) {
      const key = `intro_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('lets_get_started', key);
      }
      return;
    }

    // Outro block
    if (phase === 'outro' || (phase === 'work' && stepType === 'outro')) {
      const key = `outro_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('workout_complete_long', key);
      }
      return;
    }

    // Demo block — plays "Here's what's coming up" once on phase entry.
    if (phase === 'demo' || (phase === 'work' && stepType === 'demo')) {
      const key = `demo_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('heres_whats_coming_up', key);
      }
      return;
    }

    // Transition block. Coach-custom prose doesn't have an OpenAI clip per
    // transition yet; stay silent and log so we can see which transitions
    // need voice coverage. The `get_ready` MP3 is played for empty-instruction
    // transitions since that's a safe static cue.
    if (phase === 'transition' || (phase === 'work' && stepType === 'transition')) {
      const key = `transition_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        const instruction = current.instructionText || current.description || '';
        if (instruction) {
          logSpeechSuppressed(`transition_${currentIndex}`, instruction);
        } else {
          enqueueCue('get_ready', key);
        }
      }
      return;
    }

    // Water Break block
    if (phase === 'waterBreak' || (phase === 'work' && stepType === 'waterBreak')) {
      const key = `waterBreak_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('water_break', key);
      }
      return;
    }

    // Grab Equipment block — speak the coach-entered instruction text via
    // lazy TTS generation (same Aria voice as movement names). Falls back to
    // the static 'get_ready' cue if text is empty or generation fails.
    if (phase === 'grabEquipment' || (phase === 'work' && stepType === 'grabEquipment')) {
      const key = `grabEquipment_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        const rawText = current.grabEquipmentText || '';
        if (!rawText.trim()) {
          enqueueCue('get_ready', key);
        } else {
          const normalized = normalizeTtsText(rawText);
          const cacheKey = `${TTS_VOICE_SLUG}|${normalized}`;
          const cached = grabEquipVoiceCacheRef.current[cacheKey];
          if (cached !== undefined) {
            if (cached) {
              enqueueVoice(cached, key);
            } else {
              enqueueCue('get_ready', key);
            }
          } else if (!grabEquipGeneratingRef.current.has(cacheKey)) {
            grabEquipGeneratingRef.current.add(cacheKey);
            (async () => {
              try {
                const textHash = hashTtsText(cacheKey);
                const storagePath = `voice_cache/grab_equipment/${TTS_VOICE_SLUG}-${textHash}.mp3`;
                const fns = getFunctions(undefined, 'us-central1');
                const generateVoiceFn = httpsCallable<
                  {
                    text: string; voice: string; storagePath: string;
                    provider: string; engine: string; languageCode: string;
                    sampleRate: string; effect: string; masterSpeed: string;
                    masterPitch: string; masterVolume: string; fileStore: number;
                  },
                  { url: string; path: string }
                >(fns, 'generateVoice');
                const result = await generateVoiceFn({
                  text: normalized,
                  voice: TTS_VOICE_ID,
                  storagePath,
                  provider: TTS_PROVIDER,
                  engine: TTS_ENGINE,
                  languageCode: TTS_LANGUAGE_CODE,
                  sampleRate: TTS_SAMPLE_RATE,
                  effect: TTS_VOICE_EFFECT,
                  masterSpeed: TTS_MASTER_SPEED,
                  masterPitch: TTS_MASTER_PITCH,
                  masterVolume: TTS_MASTER_VOLUME,
                  fileStore: TTS_FILE_STORE_HOURS,
                });
                const url = result.data?.url || null;
                grabEquipVoiceCacheRef.current[cacheKey] = url;
                // Only enqueue if still on this grab-equipment step (lastSpoken
                // would have advanced if the phase transitioned away). runId
                // alone doesn't catch phase transitions (only skip/pause bump it).
                if (url && lastSpokenRef.current === key) {
                  enqueueVoice(url, key);
                }
              } catch {
                grabEquipVoiceCacheRef.current[cacheKey] = null;
              } finally {
                grabEquipGeneratingRef.current.delete(cacheKey);
              }
            })();
          }
        }
      }
      return;
    }
  }, [phase, current?.stepType, currentIndex, logSpeechSuppressed, enqueueCue, enqueueVoice, isPaused]);

  // ── Welcome message on first work phase ─────────────────────────────
  useEffect(() => {
    if (isPaused) return;
    if (phase === 'work' && currentIndex === 0 && !welcomeSpokenRef.current) {
      if (current?.stepType === 'exercise') {
        welcomeSpokenRef.current = true;
        enqueueCue('workout_starting', 'welcome');
      }
    }
  }, [phase, currentIndex, current?.stepType, enqueueCue, isPaused]);

  // ── Exercise movement announcements ────────────────────────────────
  useEffect(() => {
    if (isPaused) return;
    if (!current || current.stepType !== 'exercise') return;

    if (phase === 'work') {
      // Include swapSide in the key so the work-L → work-R transition for a
      // zero-window swap re-enters this branch (otherwise countdownSpokenRef
      // stays stuck at 0 from work-L and work-R's countdown never fires).
      const key = `work_${currentIndex}_${current.name}_${swapSide}`;
      if (lastSpokenRef.current !== key) {
        const previousKey = lastSpokenRef.current;
        lastSpokenRef.current = key;
        halfwaySpokenRef.current = false;
        countdownSpokenRef.current = -1;
        restCountdownSpokenRef.current = -1;
        // Returning from a swap window (work-L → swap → work-R OR work-L →
        // work-R directly for swapWindowSec===0): the rest before work-L
        // already had its chance to announce, so re-announcing on work-R is
        // redundant. Skip.
        const returningFromSwap = previousKey === `swap_${currentIndex}`
          || (previousKey?.startsWith(`work_${currentIndex}_${current.name}_`) ?? false);
        // Rest's voiceUrl is the primary announcement of this movement's name.
        // We only fall back to enqueueing voiceUrl on work-start when rest
        // didn't announce it (no preceding rest, or voiceUrl was empty at rest
        // time — legacy movement, mid-regen). The ref is keyed on currentIndex
        // so the check is exact (no false negatives from the previous
        // movement's restAnnounced state).
        const restAnnouncedName = restAnnouncedVoiceUrlForIndexRef.current === currentIndex;
        // Single-movement (Tabata) blocks: only announce on round 0. Subsequent
        // rounds are silent — member already knows the movement.
        const isTabataRound2Plus =
          (current as any).blockMovCount === 1 && ((current as any).blockRound ?? 0) > 0;
        if (!restAnnouncedName && !returningFromSwap && !isTabataRound2Plus) {
          // Prescription clip ("Cable Curls. 75 pounds, 15 reps.") wins over the
          // base name-only clip when the coach has set weight or reps on this
          // block-movement. Falls back cleanly if prescription URL is missing.
          if (Date.now() - lastGoEnqueuedAtRef.current < 2000) return;
          const voiceUrl = (current as any).prescriptionVoiceUrl || current.voiceUrl;
          if (voiceUrl) {
            console.info('[VOICE-AUDIT] work-start fallback voiceUrl enqueue', {
              currentIndex, name: current.name, swapSide,
              usingPrescription: !!(current as any).prescriptionVoiceUrl,
            });
            enqueueVoice(voiceUrl, `work_${currentIndex}_${current.name}_fallback`);
          } else {
            console.warn('[VOICE-AUDIT] work-start fallback skipped — voiceUrl missing', {
              currentIndex, name: current.name,
            });
          }
        }
      }
    } else if (phase === 'rest') {
      const nextName = next?.name;
      const key = `rest_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        countdownSpokenRef.current = -1;
        restCountdownSpokenRef.current = -1;
        // Synthetic "Get Ready" prep-rest step (movementIndex === -1) plays BEFORE
        // the first movement of a block.
        const isPrepRest = current?.movementIndex === -1;
        // Single-movement (Tabata) inter-round rest: skip "Next Up" + voice
        // because the next round is the same movement the member just did.
        // The prep-rest (movementIndex === -1) is exempt — it introduces the
        // movement for the first time and must announce it.
        const isTabataInterRound =
          !isPrepRest &&
          (current as any).blockMovCount === 1 &&
          next != null &&
          (next as any).blockIndex === (current as any).blockIndex;
        if (nextName && !isTabataInterRound) {
          // Two reliably-cached pieces sequenced via the queue: the static
          // `next_up` MP3, then the next movement's OpenAI voiceUrl. Both
          // succeed or fail independently — a missing voiceUrl only mutes
          // the name, not the rest-screen cue.
          enqueueCue('next_up', `rest_next_up_cue_${currentIndex}`);
          // Prefer the per-build prescription clip ("Cable Curls. 75 pounds,
          // 15 reps.") when set; otherwise fall back to the base name clip.
          const nextVoiceUrl =
            ((next as any)?.prescriptionVoiceUrl as string | undefined) ||
            ((next as any)?.voiceUrl as string | undefined);
          const upcomingIndex = currentIndex + 1;
          if (nextVoiceUrl) {
            enqueueVoice(nextVoiceUrl, `rest_next_voice_${nextName}_${currentIndex}`);
            restAnnouncedVoiceUrlForIndexRef.current = upcomingIndex;
          } else {
            console.warn('[VOICE-AUDIT] rest entry — next.voiceUrl missing (work-start will fallback)', {
              currentIndex,
              upcomingIndex,
              nextName,
            });
          }
        } else if (!isPrepRest && !isTabataInterRound) {
          enqueueCue('rest_now', `rest_${currentIndex}_rest_now`);
        }
      }
    } else if (phase === 'swap') {
      const key = `swap_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        // Always the static `switch_sides` cue on swap-entry. The combined
        // "Switch sides. 3, 2, 1. Go." / "3, 2, 1. Swap sides. Go." clips
        // were an unreliable single point of failure for short windows: if
        // the clip URL failed to load/decode in time, the entire 1–6s window
        // played silent. Static cues + standalone countdown_3 + go cover the
        // same visual sequence with four short, reliably-cached MP3s.
        enqueueCue('switch_sides', key);
      }
    } else if (phase === 'ready') {
      lastSpokenRef.current = '';
      welcomeSpokenRef.current = false;
      halfwaySpokenRef.current = false;
      countdownSpokenRef.current = -1;
    }
  }, [phase, current, current?.name, current?.stepType, current?.voiceUrl, currentIndex, swapSide, next, next?.name, enqueueCue, enqueueVoice, isPaused]);

  // ── Halfway announcement (exercise only) ───────────────────────────
  // Split-mode swap-sides movements: each side IS already a "half", so a
  // mid-side halfway cue would land at the 3/4 point of the side's clock and
  // sounds confusing. Skip it entirely for split. Duplicate-mode swap-sides
  // still gets halfway because each side runs the full duration.
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'work' || !current || current.stepType !== 'exercise') return;
    if (currentDuration <= 6) return;
    const isSplitSwap = !!current.swapSides
      && (current.swapMode === 'split' || !current.swapMode);
    if (isSplitSwap) return;
    const halfway = Math.floor(currentDuration / 2);
    if (timeLeft === halfway && !halfwaySpokenRef.current) {
      halfwaySpokenRef.current = true;
      enqueueCue('halfway', `halfway_${currentIndex}`);
    }
  }, [phase, timeLeft, currentDuration, current, enqueueCue, isPaused, currentIndex]);

  // ── Countdown voice (exercise only) ────────────────────────────────
  // Sequence at end of a work phase (all static cues — no combined clips):
  //   displayed === 3: countdown_3 ("3, 2, 1")
  //   timeLeft <= 0: trailing cue —
  //     • last movement → workout_complete
  //     • swap-L with window > 0 → silent (swap-entry effect plays switch_sides)
  //     • swap-L with window === 0 → other_side ("Other side" — sides flip instantly)
  //     • rest === 0 chain → silent (next movement's voiceUrl announces it)
  //     • next is a special block → silent (special block handles its own cue)
  //     • normal work→rest → rest ("Rest")
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'work' || !current || current.stepType !== 'exercise') return;
    if (currentDuration <= 0) return;

    const displayed = Math.max(0, Math.ceil(timeLeft));
    if (displayed === 3 && timeLeft > 0 && countdownSpokenRef.current !== 3) {
      countdownSpokenRef.current = 3;
      enqueueCue('countdown_3', `work_countdown_${currentIndex}`);
    } else if (timeLeft <= 0 && countdownSpokenRef.current !== 0) {
      countdownSpokenRef.current = 0;
      const isLastMovement = currentIndex >= total - 1;
      const nextIsSpecial = next && (next as any).stepType && (next as any).stepType !== 'exercise';
      const swapTransitionPending = !!current?.swapSides && swapSide === 'L';
      const restIsZero = (current?.restAfter ?? 0) === 0;
      if (isLastMovement) {
        enqueueCue('workout_complete', `work_end_${currentIndex}`);
      } else if (swapTransitionPending) {
        const window = swapWindowSeconds(current);
        if (window <= 0) {
          // No swap visual phase — sides flip the instant work-L hits zero.
          // The static `other_side` cue marks the flip.
          enqueueCue('other_side', `work_end_swap_0_${currentIndex}`);
        }
        // swap window > 0: swap-entry effect plays switch_sides.
      } else if (restIsZero) {
        // No rest phase — next movement's work-start voiceUrl announces it.
      } else if (!nextIsSpecial) {
        enqueueCue('rest', `work_end_${currentIndex}`);
      }
    }
  }, [phase, timeLeft, current, currentDuration, currentIndex, total, next, enqueueCue, isPaused, swapSide]);

  // ── Swap end voice (work-L → swap → work-R) ────────────────────────
  // Full spoken arc for a swap-sides transition:
  //   work-L last 3s → countdown_3 ("3, 2, 1") via work-countdown effect
  //   work-L → swap  → switch_sides ("Switch sides") via phase-transition effect
  //   swap end       → go ("Go") — flips to work-R
  //
  // The earlier in-swap countdown_3 ("3, 2, 1" during the swap visual count)
  // was dropped. For windows ≤ 6s the four-cue sequence (work-L countdown +
  // switch_sides + in-swap countdown + go) didn't fit — audio compressed and
  // overlapped or trailed past the swap-end. The visual countdown is still
  // on screen; the user already heard a 3-2-1 leading into the swap from
  // work-L's countdown, so the extra in-swap countdown was redundant noise.
  const swapEndSpokenRef = useRef<boolean>(false);
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'swap') {
      if (swapEndSpokenRef.current) swapEndSpokenRef.current = false;
      return;
    }
    if (timeLeft <= 0 && !swapEndSpokenRef.current) {
      swapEndSpokenRef.current = true;
      enqueueCue('go', `swap_end_${currentIndex}`);
    }
  }, [phase, timeLeft, currentIndex, enqueueCue, isPaused]);

  // ── Rest countdown voice (rest → next exercise only) ───────────────
  // Spoken "3, 2, 1. Go." for the rest-exit transition, as two static cues:
  //   displayed === 3 → countdown_3
  //   timeLeft <= 0  → go (only when next is a plain exercise; demo /
  //                     transition / waterBreak blocks own their cue)
  // The earlier shared "3, 2, 1. Go." combined Voicemaker clip was dropped
  // for the same reason as every other combined clip: when it stalled or
  // failed to play, the enqueue-time suppression flag silenced the static
  // `go` fallback, leaving the rest→work transition dead-air.
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'rest') return;

    const displayed = Math.max(0, Math.ceil(timeLeft));
    if (displayed === 3 && timeLeft > 0 && restCountdownSpokenRef.current !== 3) {
      restCountdownSpokenRef.current = 3;
      enqueueCue('countdown_3', `rest_countdown_${currentIndex}`);
    } else if (timeLeft <= 0 && restCountdownSpokenRef.current !== 0) {
      restCountdownSpokenRef.current = 0;
      const nextIsExercise = next
        && (!(next as any).stepType || (next as any).stepType === 'exercise');
      if (nextIsExercise) {
        lastGoEnqueuedAtRef.current = Date.now();
        enqueueCue('go', `rest_end_${currentIndex}`);
      } else {
        console.warn(
          '[useWorkoutTTS] rest→? "Go" suppressed (next is not a plain exercise)',
          {
            hasNext: !!next,
            nextStepType: (next as any)?.stepType,
            nextName: (next as any)?.name,
            currentIndex,
            timeLeft,
          },
        );
      }
    }
  }, [phase, timeLeft, next, currentIndex, enqueueCue, isPaused]);

  // ── Pause → silence any audio in flight ─────────────────────────────
  useEffect(() => {
    if (!isPaused) return;
    stopAllAudio(false);
  }, [isPaused, stopAllAudio]);

  // ── Mute → silence any audio in flight ─────────────────────────────
  // The `isMuted || ttsDisabled` guards in enqueue/pump prevent *new* cues
  // from starting, but the currently playing clip and anything already
  // queued need to be stopped / dropped immediately on mute.
  useEffect(() => {
    if (!isMuted) return;
    stopAllAudio(false);
  }, [isMuted, stopAllAudio]);

  // ── Cleanup ─────────────────────────────────────────────────────────
  useEffect(() => {
    return () => {
      runIdRef.current += 1;
      queueRef.current.length = 0;
      if (gapTimerRef.current) {
        clearTimeout(gapTimerRef.current);
        gapTimerRef.current = null;
      }
      try {
        if (currentAudioRef.current) {
          currentAudioRef.current.pause();
          currentAudioRef.current = null;
        }
        if (Platform.OS === 'web' && typeof window !== 'undefined') {
          window.speechSynthesis?.cancel();
        } else {
          Speech.stop();
        }
      } catch {}
    };
  }, []);

  return { isTTSAvailable, stopAllAudio };
}
