/**
 * useWorkoutTTS — Voice coaching hook for the Workout Player
 *
 * Audio pipeline:
 *   1. Pre-generated movement voice clips (OpenAI TTS, stored at voiceUrl)
 *   2. Static platform cues (Firebase Storage MP3s)
 *
 * Web Speech / expo-speech are intentionally NOT part of the normal audible
 * path. When a voiceUrl is missing or fails to load, we log the gap and stay
 * silent rather than speaking the text via device speech — the robotic device
 * voice sounded cheap compared to the OpenAI clips and was overlapping the
 * static cues (e.g. "Next up" MP3 + "Next up, {movement}" device speech).
 *
 * Sequencing model (queue-based, not timer-based):
 *   Every cue and voice clip is pushed onto a single FIFO queue and played
 *   one at a time. Each clip's natural `ended` event (plus a small fixed
 *   QUEUE_GAP_MS gap) triggers the next dequeue. This replaces the old
 *   setTimeout ladder (1100ms → 1800ms) that was guessing at clip lengths —
 *   under the old approach, a long movement-name voice clip would overlap
 *   with the subsequent "next up" or rest countdown because the next cue
 *   fired on a fixed timer instead of waiting for the previous audio to end.
 *
 *   Expected sequence when work → rest:
 *     [countdown_3 (work last 3s)] → [rest (work end)] →
 *     [next_up cue (rest start)] → [next movement's OpenAI voiceUrl]
 *   Expected sequence when rest → work:
 *     [countdown_3 (rest last 3s)] → [go (rest end)]
 *   Expected sequence when swap-sides L → swap → R (window ≥ 1):
 *     [countdown_3 (work-L last 3s)] → [switch_sides (swap entry)] →
 *     [(visual countdown only)] → [go (swap end)]
 *   Expected sequence when swap-sides L → R, window === 0 (no swap phase):
 *     [countdown_3 (work-L last 3s)] → [other_side (work-L end)] →
 *     work-R → [countdown_3 (work-R last 3s)] → [rest/next chain]
 *
 *   ALL combined Voicemaker phrase clips were dropped. Every clip we used to
 *   pre-warm (per-movement workRestNext / workNext / nextUp, shared
 *   workSwapOtherSide, swap-window swap-entry phrases, and the shared
 *   rest→go "3, 2, 1. Go." clip) had the same failure surface: when the clip
 *   stalled or failed to load, the suppression flag set at enqueue time
 *   silenced the static fallback, leaving the transition dead-air. The
 *   audio pipeline is now static MP3 cues + per-movement OpenAI voiceUrl
 *   clips only — each clip succeeds or fails on its own with no shared
 *   point of failure.
 *
 *   Movement-name fallback: the rest screen normally enqueues `next_up` +
 *   the next movement's voiceUrl. When voiceUrl is missing or empty at rest
 *   time (legacy movement not yet voice-generated, mid-regeneration after
 *   a rename), the work-start branch enqueues voiceUrl as a fallback so the
 *   member still hears the name once the movement begins. The
 *   restAnnouncedVoiceUrlForIndexRef tracks whether rest actually queued a
 *   non-empty voiceUrl for the upcoming index so the work-start branch
 *   knows whether to fire the fallback.
 *
 *   Invalidation rules:
 *     • Skip:  stopAllAudio() bumps runIdRef, flushes queue, stops current audio.
 *     • Pause: flushes queue + stops current audio (runIdRef NOT bumped so that
 *              anything already spoken stays tracked via lastSpokenRef).
 *     • Mute:  flushes queue; future enqueues are silently dropped.
 *     • Phase change: no forced flush — queued items from the previous phase
 *       (e.g. "rest" cue enqueued at end of work) are allowed to complete
 *       naturally. The late-voiceUrl watcher gates on `timeLeft > 3.5` so we
 *       never enqueue a long voice clip into the rest→work countdown window.
 *
 * End-of-workout audio rule (single source of truth):
 *   - If the workout has an Outro block, the long completion clip
 *     (`workout_complete_long`) plays once when the outro phase begins, and
 *     the per-exercise countdown does NOT also fire `workout_complete` for
 *     the last exercise (the outro itself is the last step).
 *   - If there is no Outro block, the short `workout_complete` MP3 plays
 *     once when the last exercise's timer hits 0. The arpeggio tone in
 *     audioCues.ts is no longer used for end-of-workout to avoid stacking.
 */
import { useEffect, useRef, useCallback, useState } from 'react';
import * as Speech from 'expo-speech';
import { Platform } from 'react-native';
import { getFunctions, httpsCallable } from 'firebase/functions';
import type { StepType } from './useWorkoutFlatten';
import { unlockAudioContext } from '../lib/audioCues';
import { normalizeTtsText, hashTtsText } from '../utils/normalizeTtsText';
import {
  TTS_PROVIDER,
  TTS_VOICE_ID,
  TTS_VOICE_EFFECT,
  TTS_VOICE_SLUG,
  TTS_ENGINE,
  TTS_LANGUAGE_CODE,
  TTS_SAMPLE_RATE,
  TTS_MASTER_SPEED,
  TTS_MASTER_PITCH,
  TTS_MASTER_VOLUME,
  TTS_FILE_STORE_HOURS,
} from '../utils/ttsProviderConfig';

// ── Static cue URL map ──────────────────────────────────────────────
// Static cues are pre-generated by scripts/regenerate-platform-cues-voicemaker.js
// (Voicemaker ai3-Aria, friendly effect) and uploaded to a provider-namespaced
// path. Re-run the script to refresh cue audio after editing the phrase text
// or the break-tag pacing in that file. The CUE_PROVIDER_SLUG must match the
// PROVIDER_SLUG constant in the regen script.
const BASE_URL =
  'https://firebasestorage.googleapis.com/v0/b/goarrive.firebasestorage.app/o/voice_cache%2Fplatform%2F';
const CUE_PROVIDER_SLUG = 'voicemaker-ai3-aria-friendly';
const CUE_URL = (name: string) => `${BASE_URL}${CUE_PROVIDER_SLUG}-${name}.mp3?alt=media`;

const CUES = {
  countdown_3: CUE_URL('countdown_3'),
  countdown_3_rest: CUE_URL('countdown_3_rest'),
  countdown_4: CUE_URL('countdown_4'),
  countdown_5: CUE_URL('countdown_5'),
  countdown_10: CUE_URL('countdown_10'),
  five_seconds: CUE_URL('five_seconds'),
  ten_seconds: CUE_URL('ten_seconds'),
  go: CUE_URL('go'),
  begin: CUE_URL('begin'),
  rest: CUE_URL('rest'),
  rest_now: CUE_URL('rest_now'),
  halfway: CUE_URL('halfway'),
  workout_complete: CUE_URL('workout_complete'),
  workout_complete_long: CUE_URL('workout_complete_long'),
  workout_starting: CUE_URL('workout_starting'),
  start_now: CUE_URL('start_now'),
  next_up: CUE_URL('next_up'),
  get_ready: CUE_URL('get_ready'),
  switch_sides: CUE_URL('switch_sides'),
  other_side: CUE_URL('other_side'),
  water_break: CUE_URL('water_break'),
  heres_whats_coming_up: CUE_URL('heres_whats_coming_up'),
  warm_up: CUE_URL('warm_up'),
  cool_down: CUE_URL('cool_down'),
  stretch: CUE_URL('stretch'),
  shake_it_out: CUE_URL('shake_it_out'),
  lets_get_started: CUE_URL('lets_get_started'),
  lets_go: CUE_URL('lets_go'),
  breathe: CUE_URL('breathe'),
  take_a_breath: CUE_URL('take_a_breath'),
  you_got_this: CUE_URL('you_got_this'),
  keep_pushing: CUE_URL('keep_pushing'),
  almost_there: CUE_URL('almost_there'),
  last_round: CUE_URL('last_round'),
  last_set: CUE_URL('last_set'),
  final_rep: CUE_URL('final_rep'),
  one_more: CUE_URL('one_more'),
  push_through: CUE_URL('push_through'),
  dig_deep: CUE_URL('dig_deep'),
  dont_stop: CUE_URL('dont_stop'),
  stay_strong: CUE_URL('stay_strong'),
} as const;

type CueKey = keyof typeof CUES;

// ── Audio pool for pre-loaded cues AND voice clips ────────────────────
// Keyed: cue items use `cue:<key>`, voice items use `voice:<url>`. Pooling
// voice clips matters as much as pooling cues — iOS Safari throttles or
// silently fails new HTMLAudioElement creations after several elements are
// alive on the page. The combined transition phrase clips are reused every
// round (per movement name + the shared restGo); without pooling, each round
// allocated a fresh element until Safari refused to actually start playback,
// the `ended` event never fired, and the queue deadlocked while still
// accepting enqueues. Pool size in a workout is bounded by unique movement
// count + the static cue keys, so unbounded growth isn't a concern.
const audioPool: Record<string, HTMLAudioElement> = {};

// ── Split gain graph: voice + music are independent on iOS ──────────────
// iOS Safari ignores HTMLAudioElement.volume / HTMLVideoElement.volume set
// from JavaScript — playback always follows the system volume, no matter
// what the JS side asks for. Web Audio API's GainNode IS honored on iOS,
// so we route audio through an AudioContext and TWO GainNodes:
//   voiceGain — cues + coach voice clips (stays at 1.0; coach voice should
//               always be audible over background music)
//   musicGain — Mubert playlist element (follows the music panel slider)
// Splitting keeps the music slider from muting coach guidance — the coach
// voice was silenced by the earlier unified-gain version and confused Devin.
//
// Wiring rules (createMediaElementSource has sharp edges):
//   - Each element can be wrapped at most once (InvalidStateError otherwise).
//   - Element MUST have `crossOrigin = 'anonymous'` set BEFORE `src` is
//     assigned. Without it, cross-origin audio (Firebase Storage / Mubert)
//     taints the graph and produces silence even with CORS response headers.
//   - AudioContext must be created inside a user gesture on iOS —
//     ensureAudioGraph() is called from unlockAudioPlayback().
export type GainBus = 'voice' | 'music';
let voiceVolume = 1;
let musicVolumeGain = 1;
let audioCtx: AudioContext | null = null;
let voiceGain: GainNode | null = null;
let musicGain: GainNode | null = null;
let mediaStreamDest: MediaStreamAudioDestinationNode | null = null;
const wiredElements = new WeakMap<HTMLMediaElement, GainBus>();

function ensureAudioGraph(): void {
  if (audioCtx && voiceGain && musicGain) return;
  if (typeof window === 'undefined') return;
  const Ctx: typeof AudioContext | undefined =
    (window as any).AudioContext || (window as any).webkitAudioContext;
  if (!Ctx) return;
  try {
    audioCtx = new Ctx();
    voiceGain = audioCtx.createGain();
    voiceGain.gain.value = voiceVolume;
    voiceGain.connect(audioCtx.destination);
    musicGain = audioCtx.createGain();
    musicGain.gain.value = musicVolumeGain;
    musicGain.connect(audioCtx.destination);
    mediaStreamDest = audioCtx.createMediaStreamDestination();
    voiceGain.connect(mediaStreamDest);
    musicGain.connect(mediaStreamDest);
    console.info('[VOICE-AUDIT] audio graph online', {
      state: audioCtx.state, voiceGain: voiceVolume, musicGain: musicVolumeGain,
    });
    // Wire everything that was created before the graph existed. Elements
    // added via applyVoiceVolume default to the voice bus; external elements
    // (music) are queued with their intended bus.
    for (const el of Object.values(audioPool)) wireToGain(el, 'voice');
    for (const el of blessedGenericPlayers) wireToGain(el, 'voice');
    for (const { el, bus } of pendingExternalWires) wireToGain(el, bus);
    pendingExternalWires.length = 0;
  } catch (err) {
    console.warn('[VOICE-AUDIT] audio graph init FAILED', { err: String(err) });
    audioCtx = null;
    voiceGain = null;
    musicGain = null;
  }
}

// External elements (music) wired via wireToGain BEFORE the graph came
// online. Held with their intended bus so ensureAudioGraph() can retro-wire
// them correctly.
const pendingExternalWires: Array<{ el: HTMLMediaElement; bus: GainBus }> = [];

// True on iOS Safari (not iOS Chrome/Firefox/Edge — those wrap WebKit but
// don't have the same AudioContext-on-background behavior).
function isIOSSafari(): boolean {
  if (typeof navigator === 'undefined') return false;
  const ua = navigator.userAgent;
  return /iP(hone|od|ad)/.test(ua) && !/CriOS|FxiOS|EdgiOS/.test(ua);
}

export function wireToGain(el: HTMLMediaElement, bus: GainBus = 'voice'): void {
  if (!el) return;
  if (wiredElements.has(el)) return;
  // iOS Safari voice-bus escape hatch: calling createMediaElementSource on
  // a voice element reroutes it through the AudioContext, which iOS Safari
  // SUSPENDS the moment Safari backgrounds. Result: voice cues went silent
  // whenever the member switched to another app (regression from the Aug 11
  // Web Audio graph work). Skipping the wire keeps voice elements on the
  // native HTMLAudioElement pipeline, which iOS keeps alive via MediaSession
  // through backgrounding. Voice bus is always 1.0 (no slider), so the
  // Web Audio graph wasn't buying us anything there anyway.
  // Music bus stays wrapped: element.volume is ignored on iOS, so GainNode
  // is the only way to power the music-panel slider. Trade-off: music dies
  // on Safari-background; voice survives. Coach guidance is what matters.
  if (bus === 'voice' && isIOSSafari()) return;
  if (!audioCtx || !voiceGain || !musicGain) {
    if (!pendingExternalWires.some((p) => p.el === el)) {
      pendingExternalWires.push({ el, bus });
    }
    return;
  }
  try {
    const src = audioCtx.createMediaElementSource(el);
    src.connect(bus === 'music' ? musicGain : voiceGain);
    wiredElements.set(el, bus);
  } catch {
    // Element already has a source node bound (either by us via a WeakSet
    // miss, or by another consumer). Nothing to do — direct playback still
    // works, but volume control on iOS is lost for this element.
  }
}

// Applied to every newly-created HTMLAudioElement in this module. Sets
// crossOrigin BEFORE any src is touched, then wires to the VOICE bus (cues
// + coach voice both live on that bus).
export function applyVoiceVolume(el: HTMLMediaElement): void {
  try { (el as any).crossOrigin = 'anonymous'; } catch {}
  try { el.volume = voiceVolume; } catch {}
  wireToGain(el, 'voice');
}

// Voice slider (currently no UI — voiceVolume stays at 1.0). Kept exported
// for a future coach-voice slider without a second refactor.
export function setVoiceVolume(v: number): void {
  const clamped = Math.min(1, Math.max(0, v));
  voiceVolume = clamped;
  if (voiceGain) {
    try { voiceGain.gain.value = clamped; } catch {}
  }
  for (const el of Object.values(audioPool)) { try { el.volume = clamped; } catch {} }
  for (const el of blessedGenericPlayers) { try { el.volume = clamped; } catch {} }
}

// Music slider handler (called from useWorkoutMusic.setVolume). On iOS this
// is the only path that actually quiets the Mubert track.
export function setMusicVolume(v: number): void {
  const clamped = Math.min(1, Math.max(0, v));
  musicVolumeGain = clamped;
  if (musicGain) {
    try { musicGain.gain.value = clamped; } catch {}
  }
}

// Returns the MediaStream carrying both voice and music output, for use as
// the audio source of the canvas-stream PiP video element (Phase 2+).
// Returns null before the audio graph is initialized.
export function getPipAudioStream(): MediaStream | null {
  return mediaStreamDest ? mediaStreamDest.stream : null;
}

// Constructor helper. `new Audio(url)` sets src synchronously, which is too
// late for crossOrigin — MediaElementAudioSourceNode would taint the graph
// and produce silence. This helper enforces the correct order:
//   Audio() → crossOrigin='anonymous' → src → wire to gain.
function createManagedAudio(url?: string): HTMLAudioElement {
  const audio: HTMLAudioElement = new (window as any).Audio();
  try { (audio as any).crossOrigin = 'anonymous'; } catch {}
  if (url) audio.src = url;
  applyVoiceVolume(audio);
  return audio;
}

// Drop every pooled element. Called when the player unmounts: pooled elements
// frozen mid-clip survive unmount (module-level pool), and on the next player
// session iOS Safari can resolve play() on a wedged element without actually
// playing, leaving all audio silent. Pooling WITHIN a single player session
// must stay — see the comment above. Also drops the blessed generic players
// and re-arms unlockAudioPlayback so the next Start tap rebuilds everything
// from scratch inside a fresh user gesture, exactly like a first session.
export function resetAudioPool(): void {
  for (const key of Object.keys(audioPool)) {
    try {
      audioPool[key].pause();
      audioPool[key].removeAttribute('src');
    } catch {}
    delete audioPool[key];
  }
  for (const el of blessedGenericPlayers) {
    try {
      el.pause();
      el.removeAttribute('src');
    } catch {}
  }
  blessedGenericPlayers.length = 0;
  audioUnlocked = false;
  stopKeepalive();
  stopGraphKeepalive();
  try { mediaStreamDest?.disconnect(); } catch {}
  mediaStreamDest = null;
}

function poolKeyForCue(key: CueKey): string {
  return `cue:${key}`;
}
function poolKeyForVoice(url: string): string {
  return `voice:${url}`;
}

function preloadCue(key: CueKey): void {
  if (Platform.OS !== 'web') return;
  if (typeof window === 'undefined') return;
  const poolKey = poolKeyForCue(key);
  if (audioPool[poolKey]) return;
  try {
    const audio = createManagedAudio(CUES[key]);
    audio.preload = 'auto';
    audioPool[poolKey] = audio;
  } catch {
    // Audio API unavailable
  }
}

// Pre-load the most commonly used cues immediately. `go` is critical: without
// it preloaded, the first rest's "Go" cue has to fetch over network on first
// use and can arrive after the work phase has already started, making the
// first rest-to-work transition silent while later rests (with `go` cached in
// audioPool) play cleanly.
// get_ready / water_break / switch_sides are here because early phases
// (grabEquipment, transition, waterBreak, swap) can fire within seconds of
// the Start tap — if the cue isn't pooled + blessed at gesture time, the
// first fetch happens at play time (late/silent on LTE).
const PRIORITY_CUES: CueKey[] = [
  'countdown_3', 'countdown_3_rest', 'rest', 'go', 'halfway',
  'workout_complete', 'next_up', 'you_got_this', 'keep_pushing',
  'almost_there', 'workout_starting', 'lets_get_started',
  'get_ready', 'water_break', 'switch_sides',
  // Special-block entry cues. These fire mid-workout, minutes after the Start
  // tap — if they aren't pooled and blessed at unlock, iOS Safari gets a
  // fresh post-gesture element whose play() rejects or stalls, and the cue is
  // silently dropped (demo's "here's what's coming up" was inaudible on
  // iPhone while every pre-blessed cue played fine).
  'heres_whats_coming_up', 'workout_complete_long',
];
if (Platform.OS === 'web' && typeof window !== 'undefined') {
  // Defer preloading slightly to not block initial render
  setTimeout(() => PRIORITY_CUES.forEach(preloadCue), 2000);
}

// ── iOS audio unlock ─────────────────────────────────────────────────
// iOS Safari only allows HTMLAudioElement.play() on elements that were
// "blessed" by a play() call issued synchronously inside a user gesture.
// All our playback is driven from useEffect timers (never a gesture), so
// without an unlock step every play() rejects with NotAllowedError and the
// queue drains silently. unlockAudioPlayback() is called from the Start
// (and pause/resume) tap handlers: it blesses every element currently in
// audioPool AND primes a small set of generic players with a silent WAV.
// Elements created AFTER the gesture (late cue pool entries, per-movement
// voice clips) can't be blessed retroactively, so pumpQueue routes them
// through the pre-blessed generic players by swapping .src — a blessed
// element stays blessed across src changes.
const blessedElements = new WeakSet<HTMLAudioElement>();
// Elements whose bless play() promise hasn't settled yet. They are muted
// mid-bless, so pumpQueue must never play them directly — resolvePlayableElement
// routes to a generic player instead. Without this, the grabEquipment entry
// cue (fired milliseconds after the Start tap) could be played while still
// muted mid-bless → silent first cue.
const blessingInFlight = new Set<HTMLAudioElement>();
// Elements the queue is actively playing. Bless settlement must not
// pause/reset an element the queue has since taken over.
const queueOwnedElements = new Set<HTMLAudioElement>();
const blessedGenericPlayers: HTMLAudioElement[] = [];
let genericPlayerCursor = 0;
let audioUnlocked = false;

// 4 data bytes of silence — enough for play() to actually start on iOS.
const SILENT_WAV =
  'data:audio/wav;base64,UklGRigAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQAAAAAAA==';

// Resume the shared AudioContext if iOS auto-suspended it on backgrounding.
// Called from useWorkoutMusic's visibility handler so the music element's
// play() lands in an active graph, not a suspended one.
export function resumeAudioGraph(): void {
  if (audioCtx && audioCtx.state === 'suspended') {
    audioCtx.resume().catch(() => {});
  }
}

// Reports the shared AudioContext's current state so the music-handoff adapter
// can poll on foreground-return: resume() is fire-and-forget, so the adapter
// waits for state==='running' before swapping playback back from the shadow
// element to the graph-wired audible one. `interrupted` is an iOS-only state
// (call interrupts) that the adapter treats the same as suspended.
export type AudioGraphState = AudioContextState | 'not-initialized';
export function getAudioContextState(): AudioGraphState {
  if (!audioCtx) return 'not-initialized';
  return audioCtx.state;
}

// ── Graph-level oscillator keepalive (B) ─────────────────────────────
// An OscillatorNode at near-zero gain connected to musicGain tells iOS that
// audio is actively running in the AudioContext, preventing the OS from
// auto-suspending the graph during long work/rest phases (> 20s of silence).
// Unlike the HTMLAudioElement keepalive below, this keepalive lives inside
// the AudioContext graph itself — so iOS cannot suspend the context without
// stopping this node, which it only does when there is truly no audio.
// Gain 0.0001 is below the hearing threshold (~90 dB below full scale at 1.0).
let graphKeepaliveOscillator: OscillatorNode | null = null;
let graphKeepaliveGain: GainNode | null = null;

function startGraphKeepalive(): void {
  if (!audioCtx || !musicGain) return;
  if (graphKeepaliveOscillator) return;
  try {
    graphKeepaliveGain = audioCtx.createGain();
    graphKeepaliveGain.gain.value = 0.0001;
    graphKeepaliveGain.connect(musicGain);
    graphKeepaliveOscillator = audioCtx.createOscillator();
    graphKeepaliveOscillator.frequency.value = 0;
    graphKeepaliveOscillator.connect(graphKeepaliveGain);
    graphKeepaliveOscillator.start();
    console.info('[VOICE-AUDIT] graph keepalive oscillator started');
  } catch (err) {
    console.warn('[VOICE-AUDIT] graph keepalive start FAILED', { err: String(err) });
    graphKeepaliveOscillator = null;
    graphKeepaliveGain = null;
  }
}

function stopGraphKeepalive(): void {
  if (graphKeepaliveOscillator) {
    try { graphKeepaliveOscillator.stop(); graphKeepaliveOscillator.disconnect(); } catch {}
    graphKeepaliveOscillator = null;
  }
  if (graphKeepaliveGain) {
    try { graphKeepaliveGain.disconnect(); } catch {}
    graphKeepaliveGain = null;
  }
}

// ── Silent keepalive loop ────────────────────────────────────────────
// iOS Safari revokes autoplay permission after ~20s with no audio playing
// (the NotAllowedError requeue in pumpQueue is the symptom). Long work/rest
// phases regularly exceed 20s, so mid-workout cues rejected with nothing to
// recover on until the member happened to tap. A continuously looping silent
// clip keeps the page's audio session active so the revocation never
// triggers, and keeps the session warm across brief backgrounding.
let keepaliveEl: HTMLAudioElement | null = null;
let keepaliveUrl: string | null = null;

// The 4-byte SILENT_WAV is too short to loop (sub-ms loop churn); build a
// 1-second 8kHz mono silent WAV at runtime instead of inlining ~11KB base64.
function makeSilentWavUrl(seconds = 1): string {
  const sampleRate = 8000;
  const numSamples = Math.floor(sampleRate * seconds);
  const buf = new ArrayBuffer(44 + numSamples);
  const view = new DataView(buf);
  const writeStr = (offset: number, s: string) => {
    for (let i = 0; i < s.length; i++) view.setUint8(offset + i, s.charCodeAt(i));
  };
  writeStr(0, 'RIFF');
  view.setUint32(4, 36 + numSamples, true);
  writeStr(8, 'WAVE');
  writeStr(12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true); // PCM
  view.setUint16(22, 1, true); // mono
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate, true);
  view.setUint16(32, 1, true);
  view.setUint16(34, 8, true);
  writeStr(36, 'data');
  view.setUint32(40, numSamples, true);
  new Uint8Array(buf, 44).fill(0x80); // 8-bit PCM silence midpoint
  return URL.createObjectURL(new Blob([buf], { type: 'audio/wav' }));
}

// Must be called from inside a user gesture (the unlock tap).
function startKeepalive(): void {
  try {
    if (!keepaliveEl) {
      keepaliveUrl = makeSilentWavUrl();
      // Keepalive stays SILENT (blob URL is same-origin, no CORS issue) and is
      // intentionally NOT wired through masterGain — routing it through the
      // graph would keep the AudioContext busy but does nothing useful, and
      // wrapping every element carries some risk on iOS. Volume control on
      // silence is moot.
      keepaliveEl = new (window as any).Audio(keepaliveUrl);
      keepaliveEl!.loop = true;
      (keepaliveEl as any).playsInline = true;
    }
    keepaliveEl!.play().then(
      () => console.info('[VOICE-AUDIT] keepalive loop playing'),
      (err: unknown) =>
        console.warn('[VOICE-AUDIT] keepalive play FAILED', { err: String(err) }),
    );
  } catch (err) {
    console.warn('[VOICE-AUDIT] keepalive setup THREW', { err: String(err) });
  }
}

// iOS pauses the loop on backgrounding / audio interruptions; call this from
// gestures and foreground-return to revive it. No-op when already playing.
export function resumeKeepalive(): void {
  if (keepaliveEl && keepaliveEl.paused) {
    keepaliveEl.play().catch(() => {});
  }
}

function stopKeepalive(): void {
  if (keepaliveEl) {
    try {
      keepaliveEl.pause();
      keepaliveEl.removeAttribute('src');
    } catch {}
    keepaliveEl = null;
  }
  if (keepaliveUrl) {
    try { URL.revokeObjectURL(keepaliveUrl); } catch {}
    keepaliveUrl = null;
  }
}

function blessElement(el: HTMLAudioElement, label: string): void {
  try {
    // Bless by playing the 4-byte silent WAV, not the element's real clip.
    // muted alone is not a guarantee of silence: iOS Safari can ignore the
    // muted property (Low Power Mode, interrupted audio sessions), which made
    // the unlock storm audible — up to 17 cue voices at once right at the
    // Start tap, for the whole window until the bless promises settled
    // (2-4s observed on a busy main thread). With a silent source there is
    // nothing audible to leak regardless of muted handling. Blessed status
    // survives the src swap back — the generic-player routing already relies
    // on that.
    const realSrc = el.src;
    const needsSwap = !!realSrc && realSrc !== SILENT_WAV;
    el.muted = true;
    if (needsSwap) el.src = SILENT_WAV;
    blessingInFlight.add(el);
    const restore = () => {
      // If the queue took this element over mid-bless (shouldn't happen —
      // resolvePlayableElement routes around in-flight elements — but
      // belt-and-braces), don't yank its playback or src.
      if (!queueOwnedElements.has(el)) {
        try { el.pause(); el.currentTime = 0; } catch {}
        if (needsSwap) {
          try { el.src = realSrc; el.preload = 'auto'; el.load(); } catch {}
        }
      }
      el.muted = false;
    };
    const p = el.play();
    if (p && typeof p.then === 'function') {
      p.then(
        () => {
          blessingInFlight.delete(el);
          restore();
          blessedElements.add(el);
          console.info('[VOICE-AUDIT] unlock bless OK', { label });
        },
        (err: unknown) => {
          blessingInFlight.delete(el);
          restore();
          console.warn('[VOICE-AUDIT] unlock bless FAILED', { label, err: String(err) });
        },
      );
    } else {
      blessingInFlight.delete(el);
      restore();
      blessedElements.add(el);
    }
  } catch (err) {
    blessingInFlight.delete(el);
    try { el.muted = false; } catch {}
    console.warn('[VOICE-AUDIT] unlock bless THREW', { label, err: String(err) });
  }
}

/**
 * Create a blessed HTMLAudioElement for music playback that iOS will keep alive
 * during backgrounding. The element is never wired to the Web Audio graph —
 * it uses the native HTMLAudioElement pipeline that iOS keeps alive via
 * MediaSession. MUST be called from inside a user-gesture stack (unlockAudioPlayback,
 * Start tap, primeShadow) so the blessElement play() is legal on iOS.
 */
export function createBlessedMusicPlayer(): HTMLAudioElement | null {
  if (typeof window === 'undefined' || typeof Audio === 'undefined') return null;
  try {
    const el: HTMLAudioElement = new (window as any).Audio();
    el.preload = 'auto';
    try { (el as any).crossOrigin = 'anonymous'; } catch {}
    blessElement(el, 'music-shadow');
    return el;
  } catch {
    return null;
  }
}

/**
 * Must be called synchronously from inside a user gesture (Start tap,
 * pause/resume tap). Idempotent — repeat calls only re-resume the WebAudio
 * context (cheap, and covers iOS re-suspending the context after backgrounding).
 */
export function unlockAudioPlayback(): void {
  if (Platform.OS !== 'web' || typeof window === 'undefined') return;
  // Web Audio graph MUST be created inside a user gesture on iOS —
  // AudioContext construction outside a gesture starts in a permanently
  // suspended state. resume() also requires a gesture. Called on every
  // gesture (idempotent internally) so a pause/resume tap can also revive
  // the context if iOS suspended it after backgrounding.
  ensureAudioGraph();
  if (audioCtx && audioCtx.state === 'suspended') {
    audioCtx.resume().catch(() => {});
  }
  if (audioUnlocked) {
    // Repeat gesture (pause/resume tap): revive the keepalive loop if iOS
    // paused it after a backgrounding or audio-session interruption.
    resumeKeepalive();
    return;
  }
  audioUnlocked = true;
  // Make sure the priority cues exist in the pool before blessing.
  PRIORITY_CUES.forEach(preloadCue);
  for (const [key, el] of Object.entries(audioPool)) blessElement(el, key);
  for (let i = 0; i < 3; i++) {
    try {
      const el: HTMLAudioElement = createManagedAudio(SILENT_WAV);
      el.preload = 'auto';
      blessElement(el, `generic_${i}`);
      blessedGenericPlayers.push(el);
    } catch (err) {
      console.warn('[VOICE-AUDIT] unlock generic player create FAILED', { err: String(err) });
    }
  }
  startKeepalive();
  startGraphKeepalive();
  console.info('[VOICE-AUDIT] unlockAudioPlayback ran', {
    pooledBlessed: Object.keys(audioPool).length,
    genericPlayers: blessedGenericPlayers.length,
  });
}

// Evict every pooled element (except any the queue currently owns). Used as
// a recovery hammer when iOS Safari wedges the page's media elements — after
// enough HTMLAudioElements are alive, every play() resolves without actually
// playing. Fresh elements created after the purge route through the blessed
// generic players, which stay untouched.
function purgeAudioPool(): void {
  let purged = 0;
  for (const key of Object.keys(audioPool)) {
    const el = audioPool[key];
    if (queueOwnedElements.has(el)) continue;
    try {
      el.pause();
      el.removeAttribute('src');
    } catch {}
    delete audioPool[key];
    purged++;
  }
  console.warn('[VOICE-AUDIT] purgeAudioPool evicted elements', { purged });
}

// Consecutive early-ended plays (stall / error / external pause / rejection).
// Reset on any clip that actually starts playing. At 3 the pool is purged —
// see purgeAudioPool.
let consecutiveFailures = 0;

// Route playback through a pre-blessed generic player when the resolved pool
// element was created after the unlock gesture (and would therefore be
// rejected by iOS). Returns the element pumpQueue should actually play.
export function resolvePlayableElement(
  audio: HTMLAudioElement,
  url: string,
): HTMLAudioElement {
  if (!audioUnlocked) return audio;
  // A mid-bless element is muted — playing it now would be silent, and the
  // bless settlement would pause/unmute it out from under us. Route around it.
  if (blessedElements.has(audio) && !blessingInFlight.has(audio)) return audio;
  if (blessedGenericPlayers.length === 0) return audio;
  const generic =
    blessedGenericPlayers[genericPlayerCursor++ % blessedGenericPlayers.length];
  try {
    // The generic may itself still be mid-bless (settles within ms of the
    // gesture) — force-unmute; the gesture's synchronous play() call is what
    // blessed it, not the promise resolution.
    generic.muted = false;
    if (generic.src !== url) {
      generic.src = url;
      generic.load();
    }
    generic.currentTime = 0;
  } catch {}
  console.info('[VOICE-AUDIT] routing via blessed generic player', {
    urlPreview: url.slice(0, 80),
  });
  return generic;
}

// Default swap window length when the movement's swapWindowSec field is
// missing or out of range. Matches DEFAULT_SWAP_WINDOW_SEC in useWorkoutTimer
// so the TTS phrase-selection logic and the timer agree on what window
// length actually plays.
const DEFAULT_SWAP_WINDOW_SEC = 5;
function swapWindowSeconds(mov: any): number {
  const raw = mov?.swapWindowSec;
  if (typeof raw === 'number' && raw >= 0 && raw <= 15) return raw;
  return DEFAULT_SWAP_WINDOW_SEC;
}

// Natural gap between consecutive clips. Not a guess at clip length — the
// queue already waits for the previous clip's `ended` event before starting
// this gap. Tightened from 220ms after the rest flow consolidated to one
// "Next up, {name}." phrase clip — the long silence between separate
// "Next up" and movement-name clips was the main offender, and 220ms
// between [rest]→[combined phrase] still felt awkward. 90ms reads as a
// natural sentence boundary without bleeding clips into each other.
export const QUEUE_GAP_MS = 90;

// Pure helpers exported for testing.
export type QueueItemKind = 'cue' | 'voice';

// Returns the gap (ms) to insert between two consecutive audio queue items.
// cue→voice = 0 so "next up, [movement]" plays as one continuous statement.
export function calcQueueGapMs(
  currentKind: QueueItemKind,
  nextItemKind: QueueItemKind | null,
): number {
  if (currentKind === 'cue' && nextItemKind === 'voice') return 0;
  return QUEUE_GAP_MS;
}

// Finds the next real exercise step after fromIndex, skipping special blocks
// AND synthetic "Get Ready" bridge steps (stepType 'exercise' but
// movementIndex === -1, inserted by useWorkoutFlatten to carry prep rest).
// Used by the grabEquipment end announcement: the step directly after a
// grabEquipment phase is often a bridge, not the movement being introduced.
export function findUpcomingExercise<
  T extends { stepType?: string; movementIndex?: number },
>(steps: readonly T[], fromIndex: number): { step: T; index: number } | null {
  for (let i = fromIndex + 1; i < steps.length; i++) {
    const s = steps[i];
    if ((!s.stepType || s.stepType === 'exercise') && s.movementIndex !== -1) {
      return { step: s, index: i };
    }
  }
  return null;
}

// Drops queue items whose runId doesn't match currentRunId.
export function filterStaleQueueItems<T extends { runId: number }>(
  items: T[],
  currentRunId: number,
): T[] {
  return items.filter((item) => item.runId === currentRunId);
}

// ── Types ────────────────────────────────────────────────────────────
type Phase = 'ready' | 'work' | 'rest' | 'swap' | 'complete'
  | 'intro' | 'outro' | 'demo' | 'transition' | 'waterBreak' | 'grabEquipment'
  | 'followAlongVideo';

type QueueItem =
  | { kind: 'cue'; key: CueKey; context: string; runId: number; retries?: number;
      onComplete?: () => void }
  | { kind: 'voice'; url: string; context: string; runId: number; retries?: number;
      onComplete?: () => void };

interface UseWorkoutTTSOptions {
  phase: Phase;
  current: {
    name: string;
    stepType?: StepType;
    instructionText?: string;
    demoMovements?: { name: string }[];
    [key: string]: any;
  } | null;
  next: { name: string; [key: string]: any } | null;
  isMuted: boolean;
  isPaused: boolean;
  ttsDisabled?: boolean;
  currentIndex: number;
  total: number;
  timeLeft: number;
  currentDuration: number;
  /**
   * Which side of a swap-sides movement we're on. Used to suppress the
   * end-of-work `rest` cue when work-L ends (the swap-phase effect plays
   * `switch_sides` immediately after), so we don't say "Rest" + "Switch sides"
   * back-to-back.
   */
  swapSide?: 'L' | 'R';
  /**
   * 1-based round counter within the current block, tracked by the timer
   * state machine. Canonical play history — used instead of the flatten
   * pass's blockRound metadata, which can diverge from what actually played
   * if the flat list shifts mid-workout.
   */
  roundNumber?: number;
  /**
   * Full flattened step list. Needed to resolve the movement a grabEquipment
   * phase introduces — the step directly after it may be a synthetic
   * "Get Ready" bridge rather than the exercise itself.
   */
  steps?: readonly {
    stepType?: StepType;
    movementIndex?: number;
    voiceUrl?: string;
    prescriptionVoiceUrl?: string;
    name?: string;
    [key: string]: any;
  }[];
}

export function useWorkoutTTS({
  phase,
  current,
  next,
  isMuted,
  isPaused,
  ttsDisabled = false,
  currentIndex,
  total,
  timeLeft,
  currentDuration,
  swapSide = 'L',
  roundNumber = 1,
  steps,
}: UseWorkoutTTSOptions) {
  const lastSpokenRef = useRef<string>('');
  const [isTTSAvailable, setIsTTSAvailable] = useState(true);
  const halfwaySpokenRef = useRef<boolean>(false);
  const countdownSpokenRef = useRef<number>(-1);
  const restCountdownSpokenRef = useRef<number>(-1);
  const welcomeSpokenRef = useRef<boolean>(false);

  // Tracks the currentIndex+1 (upcoming movement index) for which the rest
  // phase successfully enqueued a non-empty voiceUrl. Checked at work-start to
  // decide whether to fire a voiceUrl fallback — if rest's voiceUrl was empty
  // (legacy/regenerating movement), the work branch announces the name then.
  const restAnnouncedVoiceUrlForIndexRef = useRef<number>(-1);
  const lastGoEnqueuedAtRef = useRef<number>(0);
  // Index whose zero-window "Other side" cue was already enqueued early
  // (during work-L's last 3s) — the hit-zero fallback checks this so the
  // cue never double-plays for the same movement.
  const zeroSwapCueIndexRef = useRef<number>(-1);
  // Cache for grab-equipment voice URLs: normalized-text-hash → Storage URL (or null on failure)
  const grabEquipVoiceCacheRef = useRef<Record<string, string | null>>({});
  const grabEquipGeneratingRef = useRef<Set<string>>(new Set());
  // Mirror isPaused for synchronous use inside the queue pump callbacks.
  const isPausedRef = useRef(isPaused);
  useEffect(() => { isPausedRef.current = isPaused; }, [isPaused]);

  // ── Audio queue state ───────────────────────────────────────────────
  // One-item-at-a-time FIFO. Every cue and voice clip goes through this
  // queue; nothing plays out-of-band. The queue guarantees:
  //   1. Only one audio element is playing at any moment (no overlap).
  //   2. The next item starts only after the previous one's `ended` event
  //      fires (no cutoffs — we never guess at clip length).
  //   3. Skip / Mute flushes the queue atomically via a runId bump so any
  //      already-enqueued items that have become stale are discarded.
  const queueRef = useRef<QueueItem[]>([]);
  const isPlayingRef = useRef<boolean>(false);
  const currentAudioRef = useRef<HTMLAudioElement | null>(null);
  // Monotonic counter; bumped by stopAllAudio() to invalidate in-flight items.
  const runIdRef = useRef<number>(0);
  // setTimeout handle for the QUEUE_GAP_MS gap between clips — tracked so we
  // can cancel it on flush (otherwise a pending gap-timer would fire pumpQueue
  // just after a flush and start playing whatever arrived next).
  const gapTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const logSpeechSuppressed = useCallback(
    (context: string, text: string) => {
      if (isMuted || ttsDisabled || isPausedRef.current) return;
      console.warn(
        '[useWorkoutTTS] Web Speech suppressed (no OpenAI/MP3 cue available):',
        context,
        { text: text.slice(0, 120) },
      );
    },
    [isMuted, ttsDisabled],
  );

  // Plays the next queued item. Called after each `ended` event + gap, and
  // whenever a new item is enqueued while the queue is idle. Idempotent — if
  // already playing, does nothing. Drops stale items (bumped runId) without
  // playing them.
  const pumpQueue = useCallback(() => {
    if (Platform.OS !== 'web' || typeof window === 'undefined') {
      console.info('[VOICE-AUDIT] pumpQueue skipped — non-web platform');
      return;
    }
    if (isPlayingRef.current) {
      console.info('[VOICE-AUDIT] pumpQueue skipped — isPlayingRef=true', {
        queueLen: queueRef.current.length,
        nextContext: queueRef.current[0]?.context,
      });
      return;
    }
    if (isPausedRef.current || isMuted || ttsDisabled) {
      console.info('[VOICE-AUDIT] pumpQueue skipped — paused/muted/disabled', {
        isPaused: isPausedRef.current, isMuted, ttsDisabled,
        queueLen: queueRef.current.length,
      });
      return;
    }

    // Drop stale items from the head of the queue.
    let droppedStale = 0;
    while (queueRef.current.length > 0 && queueRef.current[0].runId !== runIdRef.current) {
      queueRef.current.shift();
      droppedStale++;
    }
    if (droppedStale > 0) {
      console.info('[VOICE-AUDIT] pumpQueue dropped stale items', { droppedStale });
    }
    if (queueRef.current.length === 0) {
      console.info('[VOICE-AUDIT] pumpQueue idle — queue empty');
      return;
    }

    const queueLenBefore = queueRef.current.length;
    const item = queueRef.current.shift()!;
    const queueLenAfter = queueRef.current.length;
    const url = item.kind === 'cue' ? CUES[item.key] : item.url;
    if (!url) {
      console.warn('[VOICE-AUDIT] pumpQueue dequeued empty url — skipping', {
        context: item.context, queueLenBefore, queueLenAfter,
      });
      if (item.kind === 'voice') logSpeechSuppressed(item.context, '');
      pumpQueue();
      return;
    }

    const poolKey = item.kind === 'cue' ? poolKeyForCue(item.key) : poolKeyForVoice(item.url);
    let audio: HTMLAudioElement;
    let pooledHit = false;
    try {
      const pooled = audioPool[poolKey];
      if (pooled) {
        if (pooled.readyState === 0) {
          // Stale pooled element — src set but no data loaded (expired URL,
          // CORS block, or iOS Safari cleared the buffer). Evict and recreate
          // so the fresh element triggers a real network fetch rather than
          // immediately firing MEDIA_ERR_SRC_NOT_SUPPORTED.
          try { pooled.pause(); } catch {}
          delete audioPool[poolKey];
          audio = createManagedAudio(url);
          audio.preload = 'auto';
          audioPool[poolKey] = audio;
          console.info('[VOICE-AUDIT] pumpQueue evicted stale pool entry (readyState=0)', { context: item.context, poolKey });
        } else {
          audio = pooled;
          pooledHit = true;
          try { audio.currentTime = 0; } catch {}
        }
      } else {
        audio = createManagedAudio(url);
        audio.preload = 'auto';
        audioPool[poolKey] = audio;
      }
    } catch (err) {
      console.warn('[VOICE-AUDIT] PLAY SETUP THREW', { context: item.context, err });
      pumpQueue();
      return;
    }

    // iOS: elements created after the unlock gesture would reject play(), and
    // elements still mid-bless are muted; swap to a pre-blessed generic player
    // when needed (no-op elsewhere).
    audio = resolvePlayableElement(audio, url);
    // Safety net: nothing outside the bless flow ever mutes these elements,
    // so force-unmute whatever we're about to play (mute UX is gated via
    // isMuted in enqueue/pump, not element.muted).
    try { audio.muted = false; } catch {}
    queueOwnedElements.add(audio);

    // Use AbortController to remove ended/error/playing listeners on flush so
    // a pooled element can't accumulate stale listeners across rounds (an old
    // listener firing late would mutate isPlayingRef out from under a fresh
    // play and re-pump the queue mid-clip).
    const ac =
      typeof AbortController !== 'undefined' ? new AbortController() : null;
    const listenerOpts: AddEventListenerOptions = ac
      ? { once: true, signal: ac.signal }
      : { once: true };

    isPlayingRef.current = true;
    currentAudioRef.current = audio;
    const myRunId = item.runId;
    let settled = false;
    let started = false;
    let watchdog: ReturnType<typeof setTimeout> | null = null;
    console.info('[VOICE-AUDIT] PLAY ATTEMPT', {
      context: item.context,
      kind: item.kind,
      pooledHit,
      queueLenBefore,
      queueLenAfter,
      isPlayingRef: true,
      readyState: audio.readyState,
    });

    const onDone = (reason: string, detail?: unknown) => {
      if (settled) return;
      settled = true;
      if (watchdog) { clearTimeout(watchdog); watchdog = null; }
      if (ac) {
        try { ac.abort(); } catch {}
      }
      if (reason === 'ended') {
        console.info('[VOICE-AUDIT] PLAY ENDED', { context: item.context, started });
      } else {
        console.warn('[VOICE-AUDIT] PLAY ENDED EARLY', {
          context: item.context, reason, started,
          mediaError: (audio as any).error?.code,
          detail,
        });
        // Abandoning a still-loading element without pausing it lets it start
        // playing on its own once data arrives — over the top of whatever the
        // queue plays next. Seen every workout start: the cold-cache welcome
        // clip stalls past the watchdog, the queue moves on to the movement
        // name, then the welcome clip wakes up and both play at once. pause()
        // also rejects the element's pending play() promise so it can't
        // resurrect itself later.
        try {
          audio.pause();
          audio.currentTime = 0;
        } catch {}
      }
      if (currentAudioRef.current === audio) currentAudioRef.current = null;
      queueOwnedElements.delete(audio);
      isPlayingRef.current = false;
      // Items with a completion callback (intro announcement) settle exactly
      // once, on any outcome — never requeued or retried, because the caller
      // gates the workout start on this callback and a retried replay would
      // fire it mid-workout. The callback itself must be idempotent.
      if (item.onComplete) {
        try { item.onComplete(); } catch {}
      }
      // If a flush happened (runId bumped) while we were playing, don't pump —
      // the flush already cleared the queue and we should stay quiet until the
      // next enqueue.
      if (myRunId !== runIdRef.current) return;
      if (gapTimerRef.current) clearTimeout(gapTimerRef.current);

      // iOS Safari blocks autoplay after ~20s of silence (NotAllowedError).
      // Instead of dropping the item, put it back and retry on next user tap.
      if (
        !item.onComplete &&
        reason === 'play-rejected' &&
        (detail as any)?.name === 'NotAllowedError' &&
        typeof window !== 'undefined'
      ) {
        console.info('[VOICE-AUDIT] play-rejected NotAllowedError — requeueing for next gesture', { context: item.context });
        queueRef.current.unshift(item);
        const retry = () => {
          document.removeEventListener('touchstart', retry);
          document.removeEventListener('click', retry);
          // We're inside a real gesture — also re-arm the WebAudio context
          // and the silent keepalive loop, both of which iOS may have
          // suspended alongside the HTMLAudio permission.
          unlockAudioContext();
          resumeKeepalive();
          pumpQueue();
        };
        document.addEventListener('touchstart', retry, { once: true, passive: true });
        document.addEventListener('click', retry, { once: true });
        return;
      }

      // Early failures (stall, decode error, external pause from an audio
      // interruption, non-NotAllowed rejection) used to silently drop the
      // clip. Retry each item once: the wedged element gets evicted so the
      // retry builds a fresh one, which resolvePlayableElement routes through
      // a blessed generic player.
      const retriable =
        reason === 'play-stalled' ||
        reason === 'error' ||
        reason === 'play-threw' ||
        reason === 'play-rejected' ||
        reason === 'paused-externally';
      if (retriable && !item.onComplete) {
        consecutiveFailures++;
        if (audioPool[poolKey] === audio) {
          try { audio.pause(); } catch {}
          delete audioPool[poolKey];
        }
        if ((item.retries ?? 0) < 1) {
          console.info('[VOICE-AUDIT] retrying failed clip once', { context: item.context, reason });
          queueRef.current.unshift({ ...item, retries: (item.retries ?? 0) + 1 });
        }
        if (consecutiveFailures >= 3) {
          purgeAudioPool();
          consecutiveFailures = 0;
        }
      }

      const nextItemKind = queueRef.current[0]?.kind;
      const gapMs = (item.kind === 'cue' && nextItemKind === 'voice') ? 0 : QUEUE_GAP_MS;
      gapTimerRef.current = setTimeout(() => {
        gapTimerRef.current = null;
        pumpQueue();
      }, gapMs);
    };

    audio.addEventListener('ended', () => onDone('ended'), listenerOpts);
    audio.addEventListener(
      'error',
      () => onDone('error', (audio as any).error),
      listenerOpts,
    );
    audio.addEventListener(
      'playing',
      () => {
        started = true;
        consecutiveFailures = 0;
        console.info('[VOICE-AUDIT] PLAY STARTED', {
          context: item.context,
          duration: audio.duration,
        });
      },
      listenerOpts,
    );
    // iOS pauses the element when the app backgrounds, the screen locks, or
    // another audio session interrupts (phone call, Siri, alarm, another
    // app's media). Without this listener 'ended' never fires, isPlayingRef
    // stays true forever, and the queue deadlocks — no audio for the rest of
    // the workout even though timers keep enqueueing. Natural completion also
    // fires 'pause' just before 'ended'; audio.ended distinguishes the two.
    // Our own cleanup pauses happen after settled=true / listener abort.
    audio.addEventListener(
      'pause',
      () => {
        if (audio.ended || settled) return;
        onDone('paused-externally');
      },
      listenerOpts,
    );

    try {
      const p = audio.play();
      if (p && typeof p.then === 'function') {
        p.then(
          () => {
            console.info('[VOICE-AUDIT] PLAY RESOLVED', {
              context: item.context, paused: audio.paused, started,
            });
          },
          (err: unknown) => onDone('play-rejected', err),
        );
      }
    } catch (err) {
      onDone('play-threw', err);
      return;
    }

    // Watchdog: if play() resolved but the 'playing' event never fires within
    // 5s, the audio element is wedged (iOS Safari can resolve play() without
    // actually starting playback after several elements have been created).
    // Drop the pooled element so the next play creates a fresh one, and pump
    // the next item so the queue doesn't deadlock.
    watchdog = setTimeout(() => {
      if (settled || started) return;
      console.warn('[VOICE-AUDIT] PLAY STALLED — no `playing` event in 5s', {
        context: item.context,
        readyState: audio.readyState,
        networkState: audio.networkState,
        paused: audio.paused,
        currentTime: audio.currentTime,
        mediaError: (audio as any).error?.code,
      });
      // Evict the wedged element from the pool so the next attempt for this
      // URL/cue creates a fresh HTMLAudioElement.
      if (audioPool[poolKey] === audio) {
        try { audio.pause(); } catch {}
        delete audioPool[poolKey];
      }
      onDone('play-stalled');
    }, 5000);
  }, [isMuted, ttsDisabled, logSpeechSuppressed]);

  // ── Queue API ───────────────────────────────────────────────────────
  const enqueueCue = useCallback(
    (key: CueKey, context: string = '') => {
      if (isMuted || ttsDisabled) return;
      if (Platform.OS !== 'web' || typeof window === 'undefined') return;
      queueRef.current.push({ kind: 'cue', key, context, runId: runIdRef.current });
      pumpQueue();
    },
    [isMuted, ttsDisabled, pumpQueue],
  );

  // Enqueue a dynamic voice URL (OpenAI movement clips). Empty URL logs the
  // gap and does not enqueue (nothing would play anyway).
  const enqueueVoice = useCallback(
    (url: string, context: string) => {
      if (isMuted || ttsDisabled) {
        console.warn('[VOICE-AUDIT] enqueueVoice dropped — muted/ttsDisabled', { context, isMuted, ttsDisabled });
        return;
      }
      if (Platform.OS !== 'web' || typeof window === 'undefined') return;
      if (!url) {
        console.warn('[VOICE-AUDIT] enqueueVoice dropped — empty url', { context });
        logSpeechSuppressed(context, '');
        return;
      }
      console.info('[VOICE-AUDIT] enqueueVoice queued', { context, urlPreview: url.slice(0, 80) });
      const poolKey = poolKeyForVoice(url);
      if (!audioPool[poolKey]) {
        try {
          const audio = createManagedAudio(url);
          audio.preload = 'auto';
          audioPool[poolKey] = audio;
        } catch {
          // preload failed — pumpQueue will allocate on dequeue
        }
      }
      queueRef.current.push({ kind: 'voice', url, context, runId: runIdRef.current });
      pumpQueue();
    },
    [isMuted, ttsDisabled, logSpeechSuppressed, pumpQueue],
  );

  // Play a one-off voice clip (intro announcement) through the serialized
  // queue so it can never overlap other cues. onComplete fires exactly once
  // on any outcome — including muted/unavailable, so callers can gate flow.
  const playExclusiveVoice = useCallback(
    (url: string, onComplete: () => void) => {
      if (
        isMuted || ttsDisabled || !url ||
        Platform.OS !== 'web' || typeof window === 'undefined'
      ) {
        console.warn('[VOICE-AUDIT] playExclusiveVoice skipped', { isMuted, ttsDisabled, hasUrl: !!url });
        try { onComplete(); } catch {}
        return;
      }
      console.info('[VOICE-AUDIT] playExclusiveVoice queued', { urlPreview: url.slice(0, 80) });
      const poolKey = poolKeyForVoice(url);
      if (!audioPool[poolKey]) {
        try {
          const audio = createManagedAudio(url);
          audio.preload = 'auto';
          audioPool[poolKey] = audio;
        } catch {}
      }
      queueRef.current.push({
        kind: 'voice', url, context: 'intro_announcement',
        runId: runIdRef.current, onComplete,
      });
      pumpQueue();
    },
    [isMuted, ttsDisabled, pumpQueue],
  );

  // Flush everything: bump runId so in-flight play()s drop their post-ended
  // pump, stop the currently playing audio, clear pending items, cancel the
  // inter-clip gap timer. Called from Skip (resetSpoken=true) so the new skip
  // target's cues fire fresh, and from Pause (resetSpoken=false) where we
  // keep track of what was already announced so cues don't double up on
  // resume.
  const stopAllAudio = useCallback((resetSpoken = true) => {
    runIdRef.current += 1;
    queueRef.current.length = 0;
    if (gapTimerRef.current) {
      clearTimeout(gapTimerRef.current);
      gapTimerRef.current = null;
    }
    try {
      if (currentAudioRef.current) {
        currentAudioRef.current.pause();
        try { currentAudioRef.current.currentTime = 0; } catch {}
      }
      if (Platform.OS === 'web' && typeof window !== 'undefined') {
        window.speechSynthesis?.cancel();
      } else {
        Speech.stop();
      }
    } catch {}
    currentAudioRef.current = null;
    isPlayingRef.current = false;
    if (resetSpoken) {
      countdownSpokenRef.current = -1;
      halfwaySpokenRef.current = false;
      restAnnouncedVoiceUrlForIndexRef.current = -1;
    }
  }, []);

  // On web, we always have audio (our own files). On native, check expo-speech.
  useEffect(() => {
    if (Platform.OS === 'web') {
      setIsTTSAvailable(typeof window !== 'undefined');
    } else {
      Speech.getAvailableVoicesAsync()
        .then((voices) => setIsTTSAvailable(voices.length > 0))
        .catch(() => setIsTTSAvailable(false));
    }
  }, []);

  // Recover audio when the app returns to the foreground. iOS suspends the
  // WebAudio context and pauses media elements on backgrounding; the 'pause'
  // listener in pumpQueue keeps the queue from deadlocking, but the context
  // resume and the keepalive loop still need a nudge — and if the queue went
  // idle with items pending (play rejected while hidden), kick it.
  useEffect(() => {
    if (Platform.OS !== 'web' || typeof window === 'undefined') return;
    const onVisibilityChange = () => {
      if (document.visibilityState !== 'visible') return;
      console.info('[VOICE-AUDIT] visibilitychange → visible — resuming audio');
      unlockAudioContext();
      resumeKeepalive();
      const cur = currentAudioRef.current;
      if (isPlayingRef.current && cur && cur.paused && !cur.ended) {
        // Element paused while hidden but its 'pause' event not yet
        // delivered — try resuming the clip in place. If play() rejects, the
        // pause listener settles the item and the queue moves on.
        cur.play().catch(() => {});
      } else if (!isPlayingRef.current) {
        pumpQueue();
      }
    };
    document.addEventListener('visibilitychange', onVisibilityChange);
    return () =>
      document.removeEventListener('visibilitychange', onVisibilityChange);
  }, [pumpQueue]);

  // ── Special block announcements ────────────────────────────────────
  useEffect(() => {
    if (isPaused) return;
    if (!current) return;
    const stepType = current.stepType;
    console.info('[VOICE-AUDIT] special-block-effect fired', { phase, stepType, currentIndex, lastSpoken: lastSpokenRef.current });

    // Intro block
    if (phase === 'intro' || (phase === 'work' && stepType === 'intro')) {
      const key = `intro_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('lets_get_started', key);
      }
      return;
    }

    // Outro block
    if (phase === 'outro' || (phase === 'work' && stepType === 'outro')) {
      const key = `outro_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('workout_complete_long', key);
      }
      return;
    }

    // Demo block — plays "Here's what's coming up" once on phase entry.
    if (phase === 'demo' || (phase === 'work' && stepType === 'demo')) {
      const key = `demo_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('heres_whats_coming_up', key);
      }
      return;
    }

    // Transition block. Coach-custom prose doesn't have an OpenAI clip per
    // transition yet; stay silent and log so we can see which transitions
    // need voice coverage. The `get_ready` MP3 is played for empty-instruction
    // transitions since that's a safe static cue.
    if (phase === 'transition' || (phase === 'work' && stepType === 'transition')) {
      const key = `transition_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        const instruction = current.instructionText || current.description || '';
        if (instruction) {
          logSpeechSuppressed(`transition_${currentIndex}`, instruction);
        } else {
          enqueueCue('get_ready', key);
        }
      }
      return;
    }

    // Water Break block
    if (phase === 'waterBreak' || (phase === 'work' && stepType === 'waterBreak')) {
      const key = `waterBreak_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('water_break', key);
      }
      return;
    }

    // Grab Equipment block — speak the coach-entered instruction text via
    // lazy TTS generation (same Aria voice as movement names). Falls back to
    // the static 'get_ready' cue if text is empty or generation fails.
    if (phase === 'grabEquipment' || (phase === 'work' && stepType === 'grabEquipment')) {
      const key = `grabEquipment_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        const rawText = current.grabEquipmentText || '';
        const normalized = normalizeTtsText(rawText);
        if (!normalized) {
          console.info('[VOICE-AUDIT] grab-equipment: empty text → get_ready fallback', { currentIndex });
          enqueueCue('get_ready', key);
        } else {
          const cacheKey = `${TTS_VOICE_SLUG}|${normalized}`;
          const cached = grabEquipVoiceCacheRef.current[cacheKey];
          console.info('[VOICE-AUDIT] grab-equipment: text found', { currentIndex, normalized: normalized.slice(0, 60), cacheHit: cached !== undefined });
          if (cached !== undefined) {
            if (cached) {
              enqueueVoice(cached, key);
            } else {
              // Prior generation failed — fall back to static cue
              enqueueCue('get_ready', key);
            }
          } else if (!grabEquipGeneratingRef.current.has(cacheKey)) {
            grabEquipGeneratingRef.current.add(cacheKey);
            const capturedKey = key;
            (async () => {
              try {
                const textHash = hashTtsText(cacheKey);
                const storagePath = `voice_cache/movements/grab-equip-${TTS_VOICE_SLUG}-${textHash}.mp3`;
                console.info('[VOICE-AUDIT] grab-equipment: calling generateVoice', { normalized: normalized.slice(0, 60), storagePath });
                const fns = getFunctions(undefined, 'us-central1');
                const generateVoiceFn = httpsCallable<
                  {
                    text: string; voice: string; storagePath: string;
                    provider: string; engine: string; languageCode: string;
                    sampleRate: string; effect: string; masterSpeed: string;
                    masterPitch: string; masterVolume: string; fileStore: number;
                  },
                  { url: string; path: string }
                >(fns, 'generateVoice');
                const result = await generateVoiceFn({
                  text: normalized,
                  voice: TTS_VOICE_ID,
                  storagePath,
                  provider: TTS_PROVIDER,
                  engine: TTS_ENGINE,
                  languageCode: TTS_LANGUAGE_CODE,
                  sampleRate: TTS_SAMPLE_RATE,
                  effect: TTS_VOICE_EFFECT,
                  masterSpeed: TTS_MASTER_SPEED,
                  masterPitch: TTS_MASTER_PITCH,
                  masterVolume: TTS_MASTER_VOLUME,
                  fileStore: TTS_FILE_STORE_HOURS,
                });
                const url = result.data?.url || null;
                grabEquipVoiceCacheRef.current[cacheKey] = url;
                console.info('[VOICE-AUDIT] grab-equipment: generateVoice resolved', {
                  url: url ? url.slice(0, 80) : null,
                  stillOnStep: lastSpokenRef.current === capturedKey,
                });
                // Only enqueue if still on this grab-equipment step (lastSpoken
                // would have advanced if the phase transitioned away).
                if (url && lastSpokenRef.current === capturedKey) {
                  enqueueVoice(url, capturedKey);
                } else if (!url) {
                  // Generation returned empty URL — fall back to static cue
                  if (lastSpokenRef.current === capturedKey) {
                    enqueueCue('get_ready', capturedKey);
                  }
                }
              } catch (err: any) {
                console.warn('[VOICE-AUDIT] grab-equipment: generateVoice THREW — falling back to get_ready', {
                  code: err?.code, message: err?.message,
                  details: err?.details ?? null,
                });
                grabEquipVoiceCacheRef.current[cacheKey] = null;
                if (lastSpokenRef.current === capturedKey) {
                  enqueueCue('get_ready', capturedKey);
                }
              } finally {
                grabEquipGeneratingRef.current.delete(cacheKey);
              }
            })();
          }
        }
      }
      return;
    }
  }, [phase, current?.stepType, currentIndex, logSpeechSuppressed, enqueueCue, enqueueVoice, isPaused]);

  // ── Welcome message on first work phase ─────────────────────────────
  useEffect(() => {
    if (isPaused) return;
    if (phase === 'work' && currentIndex === 0 && !welcomeSpokenRef.current) {
      if (current?.stepType === 'exercise') {
        welcomeSpokenRef.current = true;
        enqueueCue('workout_starting', 'welcome');
      }
    }
  }, [phase, currentIndex, current?.stepType, enqueueCue, isPaused]);

  // ── Exercise movement announcements ────────────────────────────────
  useEffect(() => {
    if (isPaused) return;
    if (!current || current.stepType !== 'exercise') return;

    if (phase === 'work') {
      // Include swapSide in the key so the work-L → work-R transition for a
      // zero-window swap re-enters this branch (otherwise countdownSpokenRef
      // stays stuck at 0 from work-L and work-R's countdown never fires).
      const key = `work_${currentIndex}_${current.name}_${swapSide}`;
      if (lastSpokenRef.current !== key) {
        const previousKey = lastSpokenRef.current;
        lastSpokenRef.current = key;
        halfwaySpokenRef.current = false;
        countdownSpokenRef.current = -1;
        restCountdownSpokenRef.current = -1;
        // Returning from a swap window (work-L → swap → work-R OR work-L →
        // work-R directly for swapWindowSec===0): the rest before work-L
        // already had its chance to announce, so re-announcing on work-R is
        // redundant. Skip.
        const returningFromSwap = previousKey === `swap_${currentIndex}`
          || (previousKey?.startsWith(`work_${currentIndex}_${current.name}_`) ?? false);
        // Rest's voiceUrl is the primary announcement of this movement's name.
        // We only fall back to enqueueing voiceUrl on work-start when rest
        // didn't announce it (no preceding rest, or voiceUrl was empty at rest
        // time — legacy movement, mid-regen). The ref is keyed on currentIndex
        // so the check is exact (no false negatives from the previous
        // movement's restAnnounced state).
        const restAnnouncedName = restAnnouncedVoiceUrlForIndexRef.current === currentIndex;
        // Single-movement (Tabata) blocks: only announce on round 1. Later
        // rounds are silent — member already knows the movement.
        const isTabataRound2Plus =
          (current as any).blockMovCount === 1 && roundNumber >= 2;
        if (!restAnnouncedName && !returningFromSwap && !isTabataRound2Plus) {
          // Prescription clip ("Cable Curls. 75 pounds, 15 reps.") wins over the
          // base name-only clip when the coach has set weight or reps on this
          // block-movement. Falls back cleanly if prescription URL is missing.
          if (Date.now() - lastGoEnqueuedAtRef.current < 2000) return;
          const voiceUrl = (current as any).prescriptionVoiceUrl || current.voiceUrl;
          if (voiceUrl) {
            console.info('[VOICE-AUDIT] work-start fallback voiceUrl enqueue', {
              currentIndex, name: current.name, swapSide,
              usingPrescription: !!(current as any).prescriptionVoiceUrl,
            });
            enqueueVoice(voiceUrl, `work_${currentIndex}_${current.name}_fallback`);
          } else {
            console.warn('[VOICE-AUDIT] work-start fallback skipped — voiceUrl missing', {
              currentIndex, name: current.name,
            });
          }
        }
      }
    } else if (phase === 'rest') {
      const nextName = next?.name;
      const key = `rest_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        countdownSpokenRef.current = -1;
        restCountdownSpokenRef.current = -1;
        // Synthetic "Get Ready" prep-rest step (movementIndex === -1) plays BEFORE
        // the first movement of a block.
        const isPrepRest = current?.movementIndex === -1;
        // Single-movement (Tabata) inter-round rest: skip "Next Up" + voice
        // because the next round is the same movement the member just did.
        // The prep-rest (movementIndex === -1) is exempt — it introduces the
        // movement for the first time and must announce it.
        const isTabataInterRound =
          !isPrepRest &&
          (current as any).blockMovCount === 1 &&
          next != null &&
          (next as any).blockIndex === (current as any).blockIndex;
        // Duplicate suppression: a preceding grabEquipment phase may have
        // already announced this same upcoming movement at its end ("Next
        // up, X"). It records the announced flat index in
        // restAnnouncedVoiceUrlForIndexRef — if that matches our upcoming
        // index, skip the rest-entry announcement entirely.
        const grabAlreadyAnnounced =
          restAnnouncedVoiceUrlForIndexRef.current === currentIndex + 1;
        if (nextName && !isTabataInterRound && !grabAlreadyAnnounced) {
          // Two reliably-cached pieces sequenced via the queue: the static
          // `next_up` MP3, then the next movement's OpenAI voiceUrl. Both
          // succeed or fail independently — a missing voiceUrl only mutes
          // the name, not the rest-screen cue.
          enqueueCue('next_up', `rest_next_up_cue_${currentIndex}`);
          // Prefer the per-build prescription clip ("Cable Curls. 75 pounds,
          // 15 reps.") when set; otherwise fall back to the base name clip.
          const nextVoiceUrl =
            ((next as any)?.prescriptionVoiceUrl as string | undefined) ||
            ((next as any)?.voiceUrl as string | undefined);
          const upcomingIndex = currentIndex + 1;
          if (nextVoiceUrl) {
            enqueueVoice(nextVoiceUrl, `rest_next_voice_${nextName}_${currentIndex}`);
            restAnnouncedVoiceUrlForIndexRef.current = upcomingIndex;
          } else {
            console.warn('[VOICE-AUDIT] rest entry — next.voiceUrl missing (work-start will fallback)', {
              currentIndex,
              upcomingIndex,
              nextName,
            });
          }
        } else if (!isPrepRest && !isTabataInterRound) {
          enqueueCue('rest_now', `rest_${currentIndex}_rest_now`);
        }
      }
    } else if (phase === 'swap') {
      const key = `swap_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        // Always the static `switch_sides` cue on swap-entry. The combined
        // "Switch sides. 3, 2, 1. Go." / "3, 2, 1. Swap sides. Go." clips
        // were an unreliable single point of failure for short windows: if
        // the clip URL failed to load/decode in time, the entire 1–6s window
        // played silent. Static cues + standalone countdown_3 + go cover the
        // same visual sequence with four short, reliably-cached MP3s.
        enqueueCue('switch_sides', key);
      }
    } else if (phase === 'ready') {
      lastSpokenRef.current = '';
      welcomeSpokenRef.current = false;
      halfwaySpokenRef.current = false;
      countdownSpokenRef.current = -1;
    }
  }, [phase, current, current?.name, current?.stepType, current?.voiceUrl, currentIndex, swapSide, next, next?.name, roundNumber, enqueueCue, enqueueVoice, isPaused]);

  // ── Halfway announcement (exercise only) ───────────────────────────
  // Split-mode swap-sides movements: each side IS already a "half", so a
  // mid-side halfway cue would land at the 3/4 point of the side's clock and
  // sounds confusing. Skip it entirely for split. Duplicate-mode swap-sides
  // still gets halfway because each side runs the full duration.
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'work' || !current || current.stepType !== 'exercise') return;
    if (currentDuration <= 6) return;
    const isSplitSwap = !!current.swapSides
      && (current.swapMode === 'split' || !current.swapMode);
    if (isSplitSwap) return;
    const halfway = Math.floor(currentDuration / 2);
    if (timeLeft === halfway && !halfwaySpokenRef.current) {
      halfwaySpokenRef.current = true;
      enqueueCue('halfway', `halfway_${currentIndex}`);
    }
  }, [phase, timeLeft, currentDuration, current, enqueueCue, isPaused, currentIndex]);

  // ── Countdown voice (exercise only) ────────────────────────────────
  // Sequence at end of a work phase (all static cues — no combined clips):
  //   displayed === 3: countdown_3 ("3, 2, 1")
  //   timeLeft <= 0: trailing cue —
  //     • last movement → workout_complete
  //     • swap-L with window > 0 → silent (swap-entry effect plays switch_sides)
  //     • swap-L with window === 0 → other_side ("Other side" — sides flip instantly)
  //     • rest === 0 chain → silent (next movement's voiceUrl announces it)
  //     • next is a special block → silent (special block handles its own cue)
  //     • normal work→rest → rest ("Rest")
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'work' || !current || current.stepType !== 'exercise') return;
    if (currentDuration <= 0) return;

    const displayed = Math.max(0, Math.ceil(timeLeft));
    if (displayed === 3 && timeLeft > 0 && countdownSpokenRef.current !== 3) {
      countdownSpokenRef.current = 3;
      enqueueCue('countdown_3', `work_countdown_${currentIndex}`);
      // Zero-window swap: enqueue "Other side" now, while still in work-L.
      // Enqueuing from the timeLeft<=0 branch raced the timer's phase flip —
      // the cue could land in the queue after work-R had begun and play late
      // or overlap the next announcement. Queuing it behind countdown_3 here
      // guarantees FIFO order: "3, 2, 1" then "Other side" right at the flip.
      if (currentIndex < total - 1 && !!current?.swapSides && swapSide === 'L'
          && swapWindowSeconds(current) <= 0) {
        zeroSwapCueIndexRef.current = currentIndex;
        enqueueCue('other_side', `work_end_swap_0_${currentIndex}`);
      }
    } else if (timeLeft <= 0 && countdownSpokenRef.current !== 0) {
      countdownSpokenRef.current = 0;
      const isLastMovement = currentIndex >= total - 1;
      const nextIsSpecial = next && (next as any).stepType && (next as any).stepType !== 'exercise';
      const swapTransitionPending = !!current?.swapSides && swapSide === 'L';
      const restIsZero = (current?.restAfter ?? 0) === 0;
      if (isLastMovement) {
        enqueueCue('workout_complete', `work_end_${currentIndex}`);
      } else if (swapTransitionPending) {
        const window = swapWindowSeconds(current);
        if (window <= 0 && zeroSwapCueIndexRef.current !== currentIndex) {
          // Fallback for sides too short for the displayed===3 enqueue above
          // (side duration < 3s): fire at the flip itself.
          enqueueCue('other_side', `work_end_swap_0_${currentIndex}`);
        }
        // swap window > 0: swap-entry effect plays switch_sides.
      } else if (restIsZero) {
        // No rest phase — next movement's work-start voiceUrl announces it.
      } else if (!nextIsSpecial) {
        enqueueCue('rest', `work_end_${currentIndex}`);
      }
    }
  }, [phase, timeLeft, current, currentDuration, currentIndex, total, next, enqueueCue, isPaused, swapSide]);

  // ── Swap end voice (work-L → swap → work-R) ────────────────────────
  // Full spoken arc for a swap-sides transition:
  //   work-L last 3s → countdown_3 ("3, 2, 1") via work-countdown effect
  //   work-L → swap  → switch_sides ("Switch sides") via phase-transition effect
  //   swap end       → go ("Go") — flips to work-R
  //
  // The earlier in-swap countdown_3 ("3, 2, 1" during the swap visual count)
  // was dropped. For windows ≤ 6s the four-cue sequence (work-L countdown +
  // switch_sides + in-swap countdown + go) didn't fit — audio compressed and
  // overlapped or trailed past the swap-end. The visual countdown is still
  // on screen; the user already heard a 3-2-1 leading into the swap from
  // work-L's countdown, so the extra in-swap countdown was redundant noise.
  const swapEndSpokenRef = useRef<boolean>(false);
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'swap') {
      if (swapEndSpokenRef.current) swapEndSpokenRef.current = false;
      return;
    }
    if (timeLeft <= 0 && !swapEndSpokenRef.current) {
      swapEndSpokenRef.current = true;
      enqueueCue('go', `swap_end_${currentIndex}`);
    }
  }, [phase, timeLeft, currentIndex, enqueueCue, isPaused]);

  // ── Timed special-phase countdown (grabEquipment) ───────────────────
  // grabEquipment is a timed phase that rolls straight into the next step,
  // but the work/rest countdown effects are gated to their own phases, so
  // the transition out of it was silent. Sequence: countdown_3 at
  // displayed===3, then at 0 → "Next up, [movement]" — NOT "go", because
  // grab equipment INTRODUCES the next movement rather than starting it
  // (a Get Ready bridge / prep rest usually follows before the work phase).
  // The announced movement is resolved by scanning forward past bridge
  // steps; restAnnouncedVoiceUrlForIndexRef is set so the following rest
  // bridge and work-start branches don't announce the same movement again.
  const specialCountdownSpokenRef = useRef<number>(-1);
  useEffect(() => {
    if (isPaused) return;
    const isGrabEquipment = phase === 'grabEquipment'
      || (phase === 'work' && current?.stepType === 'grabEquipment');
    if (!isGrabEquipment) {
      specialCountdownSpokenRef.current = -1;
      return;
    }
    const displayed = Math.max(0, Math.ceil(timeLeft));
    if (displayed === 3 && timeLeft > 0 && specialCountdownSpokenRef.current !== 3) {
      specialCountdownSpokenRef.current = 3;
      enqueueCue('countdown_3', `grabEquipment_countdown_${currentIndex}`);
    } else if (timeLeft <= 0 && specialCountdownSpokenRef.current !== 0) {
      specialCountdownSpokenRef.current = 0;
      // Only announce when what follows is the exercise flow (a plain
      // exercise or a Get Ready bridge). If another special block follows
      // (demo, water break…), it owns its entry cue — stay silent.
      const nextIsExerciseFlow = next
        && (!(next as any).stepType || (next as any).stepType === 'exercise');
      if (nextIsExerciseFlow) {
        const upcoming = findUpcomingExercise(steps ?? [], currentIndex);
        if (upcoming) {
          enqueueCue('next_up', `grabEquipment_end_next_up_${currentIndex}`);
          const voiceUrl =
            (upcoming.step as any).prescriptionVoiceUrl || (upcoming.step as any).voiceUrl;
          if (voiceUrl) {
            enqueueVoice(voiceUrl, `grabEquipment_end_voice_${currentIndex}`);
            restAnnouncedVoiceUrlForIndexRef.current = upcoming.index;
          } else {
            console.warn('[VOICE-AUDIT] grabEquipment end — upcoming voiceUrl missing', {
              currentIndex, upcomingIndex: upcoming.index, name: (upcoming.step as any).name,
            });
          }
        }
      }
    }
  }, [phase, timeLeft, current?.stepType, next, currentIndex, steps, enqueueCue, enqueueVoice, isPaused]);

  // ── Rest countdown voice (rest → next exercise only) ───────────────
  // Spoken "3, 2, 1. Go." for the rest-exit transition, as two static cues:
  //   displayed === 3 → countdown_3
  //   timeLeft <= 0  → go (only when next is a plain exercise; demo /
  //                     transition / waterBreak blocks own their cue)
  // The earlier shared "3, 2, 1. Go." combined Voicemaker clip was dropped
  // for the same reason as every other combined clip: when it stalled or
  // failed to play, the enqueue-time suppression flag silenced the static
  // `go` fallback, leaving the rest→work transition dead-air.
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'rest') return;

    const displayed = Math.max(0, Math.ceil(timeLeft));
    if (displayed === 3 && timeLeft > 0 && restCountdownSpokenRef.current !== 3) {
      restCountdownSpokenRef.current = 3;
      enqueueCue('countdown_3', `rest_countdown_${currentIndex}`);
    } else if (timeLeft <= 0 && restCountdownSpokenRef.current !== 0) {
      restCountdownSpokenRef.current = 0;
      const nextIsExercise = next
        && (!(next as any).stepType || (next as any).stepType === 'exercise');
      if (nextIsExercise) {
        lastGoEnqueuedAtRef.current = Date.now();
        enqueueCue('go', `rest_end_${currentIndex}`);
      } else {
        console.warn(
          '[useWorkoutTTS] rest→? "Go" suppressed (next is not a plain exercise)',
          {
            hasNext: !!next,
            nextStepType: (next as any)?.stepType,
            nextName: (next as any)?.name,
            currentIndex,
            timeLeft,
          },
        );
      }
    }
  }, [phase, timeLeft, next, currentIndex, enqueueCue, isPaused]);

  // ── Pause → silence any audio in flight ─────────────────────────────
  useEffect(() => {
    if (!isPaused) return;
    stopAllAudio(false);
  }, [isPaused, stopAllAudio]);

  // ── Mute → silence any audio in flight ─────────────────────────────
  // The `isMuted || ttsDisabled` guards in enqueue/pump prevent *new* cues
  // from starting, but the currently playing clip and anything already
  // queued need to be stopped / dropped immediately on mute.
  useEffect(() => {
    if (!isMuted) return;
    stopAllAudio(false);
  }, [isMuted, stopAllAudio]);

  // ── Cleanup ─────────────────────────────────────────────────────────
  useEffect(() => {
    return () => {
      runIdRef.current += 1;
      queueRef.current.length = 0;
      if (gapTimerRef.current) {
        clearTimeout(gapTimerRef.current);
        gapTimerRef.current = null;
      }
      try {
        if (currentAudioRef.current) {
          currentAudioRef.current.pause();
          currentAudioRef.current = null;
        }
        if (Platform.OS === 'web' && typeof window !== 'undefined') {
          window.speechSynthesis?.cancel();
        } else {
          Speech.stop();
        }
      } catch {}
      // The player unmounts on close in every surface (preview, member play,
      // share link), so this is the leave-player path: drop the pooled
      // elements so the next session starts with fresh ones.
      resetAudioPool();
    };
  }, []);

  return { isTTSAvailable, stopAllAudio, playExclusiveVoice };
}
