/**
 * useWorkoutTTS — Voice coaching hook for the Workout Player
 *
 * Audio pipeline:
 *   1. Pre-generated movement voice clips (OpenAI TTS, stored at voiceUrl)
 *   2. Static platform cues (Firebase Storage MP3s)
 *
 * Web Speech / expo-speech are intentionally NOT part of the normal audible
 * path. When a voiceUrl is missing or fails to load, we log the gap and stay
 * silent rather than speaking the text via device speech — the robotic device
 * voice sounded cheap compared to the OpenAI clips and was overlapping the
 * static cues (e.g. "Next up" MP3 + "Next up, {movement}" device speech).
 *
 * Sequencing model (queue-based, not timer-based):
 *   Every cue and voice clip is pushed onto a single FIFO queue and played
 *   one at a time. Each clip's natural `ended` event (plus a small fixed
 *   QUEUE_GAP_MS gap) triggers the next dequeue. This replaces the old
 *   setTimeout ladder (1100ms → 1800ms) that was guessing at clip lengths —
 *   under the old approach, a long movement-name voice clip would overlap
 *   with the subsequent "next up" or rest countdown because the next cue
 *   fired on a fixed timer instead of waiting for the previous audio to end.
 *
 *   Expected sequence when work → rest:
 *     Preferred (combined clip ready):
 *       [combined "3, 2, 1. Rest. Next up, {name}." Voicemaker clip]
 *       — one breath, enqueued at work timeLeft===3 via enqueueVoice.
 *     Fallback (combined clip not ready, swap sides pending, or last movement):
 *       [countdown_3] → [rest] → [combined "Next up, {name}." phrase clip]
 *       (each item waits for the previous `ended` event + QUEUE_GAP_MS)
 *     See useTransitionPhrases / generateTransitionPhrase.
 *   Expected sequence when rest → work:
 *     Preferred (combined clip ready):
 *       [combined "3, 2, 1. Go." Voicemaker clip]
 *     Fallback:
 *       [countdown_3 (rest)] → [go]
 *
 *   Invalidation rules:
 *     • Skip:  stopAllAudio() bumps runIdRef, flushes queue, stops current audio.
 *     • Pause: flushes queue + stops current audio (runIdRef NOT bumped so that
 *              anything already spoken stays tracked via lastSpokenRef).
 *     • Mute:  flushes queue; future enqueues are silently dropped.
 *     • Phase change: no forced flush — queued items from the previous phase
 *       (e.g. "rest" cue enqueued at end of work) are allowed to complete
 *       naturally. The late-voiceUrl watcher gates on `timeLeft > 3.5` so we
 *       never enqueue a long voice clip into the rest→work countdown window.
 *
 * End-of-workout audio rule (single source of truth):
 *   - If the workout has an Outro block, the long completion clip
 *     (`workout_complete_long`) plays once when the outro phase begins, and
 *     the per-exercise countdown does NOT also fire `workout_complete` for
 *     the last exercise (the outro itself is the last step).
 *   - If there is no Outro block, the short `workout_complete` MP3 plays
 *     once when the last exercise's timer hits 0. The arpeggio tone in
 *     audioCues.ts is no longer used for end-of-workout to avoid stacking.
 */
import { useEffect, useRef, useCallback, useState } from 'react';
import * as Speech from 'expo-speech';
import { Platform } from 'react-native';
import type { StepType } from './useWorkoutFlatten';

// ── Static cue URL map ──────────────────────────────────────────────
// Static cues are pre-generated by scripts/regenerate-platform-cues-voicemaker.js
// (Voicemaker ai3-Aria, friendly effect) and uploaded to a provider-namespaced
// path. Re-run the script to refresh cue audio after editing the phrase text
// or the break-tag pacing in that file. The CUE_PROVIDER_SLUG must match the
// PROVIDER_SLUG constant in the regen script.
const BASE_URL =
  'https://firebasestorage.googleapis.com/v0/b/goarrive.firebasestorage.app/o/voice_cache%2Fplatform%2F';
const CUE_PROVIDER_SLUG = 'voicemaker-ai3-aria-friendly';
const CUE_URL = (name: string) => `${BASE_URL}${CUE_PROVIDER_SLUG}-${name}.mp3?alt=media`;

const CUES = {
  countdown_3: CUE_URL('countdown_3'),
  countdown_3_rest: CUE_URL('countdown_3_rest'),
  countdown_4: CUE_URL('countdown_4'),
  countdown_5: CUE_URL('countdown_5'),
  countdown_10: CUE_URL('countdown_10'),
  five_seconds: CUE_URL('five_seconds'),
  ten_seconds: CUE_URL('ten_seconds'),
  go: CUE_URL('go'),
  begin: CUE_URL('begin'),
  rest: CUE_URL('rest'),
  rest_now: CUE_URL('rest_now'),
  halfway: CUE_URL('halfway'),
  workout_complete: CUE_URL('workout_complete'),
  workout_complete_long: CUE_URL('workout_complete_long'),
  workout_starting: CUE_URL('workout_starting'),
  start_now: CUE_URL('start_now'),
  next_up: CUE_URL('next_up'),
  get_ready: CUE_URL('get_ready'),
  switch_sides: CUE_URL('switch_sides'),
  other_side: CUE_URL('other_side'),
  water_break: CUE_URL('water_break'),
  warm_up: CUE_URL('warm_up'),
  cool_down: CUE_URL('cool_down'),
  stretch: CUE_URL('stretch'),
  shake_it_out: CUE_URL('shake_it_out'),
  lets_get_started: CUE_URL('lets_get_started'),
  lets_go: CUE_URL('lets_go'),
  breathe: CUE_URL('breathe'),
  take_a_breath: CUE_URL('take_a_breath'),
  you_got_this: CUE_URL('you_got_this'),
  keep_pushing: CUE_URL('keep_pushing'),
  almost_there: CUE_URL('almost_there'),
  last_round: CUE_URL('last_round'),
  last_set: CUE_URL('last_set'),
  final_rep: CUE_URL('final_rep'),
  one_more: CUE_URL('one_more'),
  push_through: CUE_URL('push_through'),
  dig_deep: CUE_URL('dig_deep'),
  dont_stop: CUE_URL('dont_stop'),
  stay_strong: CUE_URL('stay_strong'),
} as const;

type CueKey = keyof typeof CUES;

// ── Audio pool for pre-loaded cues AND voice clips ────────────────────
// Keyed: cue items use `cue:<key>`, voice items use `voice:<url>`. Pooling
// voice clips matters as much as pooling cues — iOS Safari throttles or
// silently fails new HTMLAudioElement creations after several elements are
// alive on the page. The combined transition phrase clips are reused every
// round (per movement name + the shared restGo); without pooling, each round
// allocated a fresh element until Safari refused to actually start playback,
// the `ended` event never fired, and the queue deadlocked while still
// accepting enqueues. Pool size in a workout is bounded by unique movement
// count + the static cue keys, so unbounded growth isn't a concern.
const audioPool: Record<string, HTMLAudioElement> = {};

function poolKeyForCue(key: CueKey): string {
  return `cue:${key}`;
}
function poolKeyForVoice(url: string): string {
  return `voice:${url}`;
}

function preloadCue(key: CueKey): void {
  if (Platform.OS !== 'web') return;
  if (typeof window === 'undefined') return;
  const poolKey = poolKeyForCue(key);
  if (audioPool[poolKey]) return;
  try {
    const audio = new (window as any).Audio(CUES[key]);
    audio.preload = 'auto';
    audioPool[poolKey] = audio;
  } catch {
    // Audio API unavailable
  }
}

// Pre-load the most commonly used cues immediately. `go` is critical: without
// it preloaded, the first rest's "Go" cue has to fetch over network on first
// use and can arrive after the work phase has already started, making the
// first rest-to-work transition silent while later rests (with `go` cached in
// audioPool) play cleanly.
const PRIORITY_CUES: CueKey[] = [
  'countdown_3', 'countdown_3_rest', 'rest', 'go', 'halfway',
  'workout_complete', 'next_up', 'you_got_this', 'keep_pushing',
  'almost_there', 'workout_starting', 'lets_get_started',
];
if (Platform.OS === 'web' && typeof window !== 'undefined') {
  // Defer preloading slightly to not block initial render
  setTimeout(() => PRIORITY_CUES.forEach(preloadCue), 2000);
}

// Natural gap between consecutive clips. Not a guess at clip length — the
// queue already waits for the previous clip's `ended` event before starting
// this gap. Tightened from 220ms after the rest flow consolidated to one
// "Next up, {name}." phrase clip — the long silence between separate
// "Next up" and movement-name clips was the main offender, and 220ms
// between [rest]→[combined phrase] still felt awkward. 90ms reads as a
// natural sentence boundary without bleeding clips into each other.
const QUEUE_GAP_MS = 90;

// ── Types ────────────────────────────────────────────────────────────
type Phase = 'ready' | 'work' | 'rest' | 'swap' | 'complete'
  | 'intro' | 'outro' | 'demo' | 'transition' | 'waterBreak' | 'grabEquipment';

type QueueItem =
  | { kind: 'cue'; key: CueKey; context: string; runId: number }
  | { kind: 'voice'; url: string; context: string; runId: number };

interface UseWorkoutTTSOptions {
  phase: Phase;
  current: {
    name: string;
    stepType?: StepType;
    instructionText?: string;
    demoMovements?: { name: string }[];
    [key: string]: any;
  } | null;
  next: { name: string; [key: string]: any } | null;
  isMuted: boolean;
  isPaused: boolean;
  ttsDisabled?: boolean;
  currentIndex: number;
  total: number;
  timeLeft: number;
  currentDuration: number;
  /**
   * Pre-warmed combined "3, 2, 1. Go." clip URL. When present, the player
   * enqueues this single clip at rest timeLeft===3 instead of countdown_3
   * at rest timeLeft===3 + separate `go` at rest timeLeft<=0. When null
   * (clip still generating or failed), the old two-clip sequence plays.
   */
  restGoVoiceUrl?: string | null;
}

export function useWorkoutTTS({
  phase,
  current,
  next,
  isMuted,
  isPaused,
  ttsDisabled = false,
  currentIndex,
  total,
  timeLeft,
  currentDuration,
  restGoVoiceUrl = null,
}: UseWorkoutTTSOptions) {
  const lastSpokenRef = useRef<string>('');
  const [isTTSAvailable, setIsTTSAvailable] = useState(true);
  const halfwaySpokenRef = useRef<boolean>(false);
  const countdownSpokenRef = useRef<number>(-1);
  const restCountdownSpokenRef = useRef<number>(-1);
  const welcomeSpokenRef = useRef<boolean>(false);

  // Records the rest phase we're waiting on a combined "Next up, {name}."
  // phrase clip for. Pre-warm normally has it ready by rest-entry, but on
  // first-ever encounter the phrase generation may still be in flight — in
  // that case we rest silent and a separate effect enqueues the clip when
  // its URL arrives via state, provided we still have enough rest time left.
  const pendingNextUpPhraseRef = useRef<
    { restKey: string; movementId: string; name: string; context: string } | null
  >(null);

  // When the combined "3, 2, 1. Rest. Next up, {name}." clip fires at work
  // timeLeft===3, stores the currentIndex. Checked at work timeLeft<=0 to
  // suppress the standalone `rest` cue, and at rest-entry to suppress the
  // standalone next-up phrase. Cleared by skip (via stopAllAudio) so a fresh
  // skip target runs the combined-or-fallback decision again.
  const combinedWorkRestFiredIndexRef = useRef<number>(-1);
  // When the combined "3, 2, 1. Go." clip fires at rest timeLeft===3, stores
  // the currentIndex. Checked at rest timeLeft<=0 to suppress the standalone
  // `go` cue.
  const combinedRestGoFiredIndexRef = useRef<number>(-1);

  // Mirror isPaused for synchronous use inside the queue pump callbacks.
  const isPausedRef = useRef(isPaused);
  useEffect(() => { isPausedRef.current = isPaused; }, [isPaused]);

  // ── Audio queue state ───────────────────────────────────────────────
  // One-item-at-a-time FIFO. Every cue and voice clip goes through this
  // queue; nothing plays out-of-band. The queue guarantees:
  //   1. Only one audio element is playing at any moment (no overlap).
  //   2. The next item starts only after the previous one's `ended` event
  //      fires (no cutoffs — we never guess at clip length).
  //   3. Skip / Mute flushes the queue atomically via a runId bump so any
  //      already-enqueued items that have become stale are discarded.
  const queueRef = useRef<QueueItem[]>([]);
  const isPlayingRef = useRef<boolean>(false);
  const currentAudioRef = useRef<HTMLAudioElement | null>(null);
  // Monotonic counter; bumped by stopAllAudio() to invalidate in-flight items.
  const runIdRef = useRef<number>(0);
  // setTimeout handle for the QUEUE_GAP_MS gap between clips — tracked so we
  // can cancel it on flush (otherwise a pending gap-timer would fire pumpQueue
  // just after a flush and start playing whatever arrived next).
  const gapTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const logSpeechSuppressed = useCallback(
    (context: string, text: string) => {
      if (isMuted || ttsDisabled || isPausedRef.current) return;
      console.warn(
        '[useWorkoutTTS] Web Speech suppressed (no OpenAI/MP3 cue available):',
        context,
        { text: text.slice(0, 120) },
      );
    },
    [isMuted, ttsDisabled],
  );

  // Plays the next queued item. Called after each `ended` event + gap, and
  // whenever a new item is enqueued while the queue is idle. Idempotent — if
  // already playing, does nothing. Drops stale items (bumped runId) without
  // playing them.
  const pumpQueue = useCallback(() => {
    if (Platform.OS !== 'web' || typeof window === 'undefined') {
      console.info('[VOICE-AUDIT] pumpQueue skipped — non-web platform');
      return;
    }
    if (isPlayingRef.current) {
      console.info('[VOICE-AUDIT] pumpQueue skipped — isPlayingRef=true', {
        queueLen: queueRef.current.length,
        nextContext: queueRef.current[0]?.context,
      });
      return;
    }
    if (isPausedRef.current || isMuted || ttsDisabled) {
      console.info('[VOICE-AUDIT] pumpQueue skipped — paused/muted/disabled', {
        isPaused: isPausedRef.current, isMuted, ttsDisabled,
        queueLen: queueRef.current.length,
      });
      return;
    }

    // Drop stale items from the head of the queue.
    let droppedStale = 0;
    while (queueRef.current.length > 0 && queueRef.current[0].runId !== runIdRef.current) {
      queueRef.current.shift();
      droppedStale++;
    }
    if (droppedStale > 0) {
      console.info('[VOICE-AUDIT] pumpQueue dropped stale items', { droppedStale });
    }
    if (queueRef.current.length === 0) {
      console.info('[VOICE-AUDIT] pumpQueue idle — queue empty');
      return;
    }

    const queueLenBefore = queueRef.current.length;
    const item = queueRef.current.shift()!;
    const queueLenAfter = queueRef.current.length;
    const url = item.kind === 'cue' ? CUES[item.key] : item.url;
    if (!url) {
      console.warn('[VOICE-AUDIT] pumpQueue dequeued empty url — skipping', {
        context: item.context, queueLenBefore, queueLenAfter,
      });
      if (item.kind === 'voice') logSpeechSuppressed(item.context, '');
      pumpQueue();
      return;
    }

    const poolKey = item.kind === 'cue' ? poolKeyForCue(item.key) : poolKeyForVoice(item.url);
    let audio: HTMLAudioElement;
    let pooledHit = false;
    try {
      const pooled = audioPool[poolKey];
      if (pooled) {
        audio = pooled;
        pooledHit = true;
        try { audio.currentTime = 0; } catch {}
      } else {
        audio = new (window as any).Audio(url);
        audio.preload = 'auto';
        audioPool[poolKey] = audio;
      }
    } catch (err) {
      console.warn('[VOICE-AUDIT] PLAY SETUP THREW', { context: item.context, err });
      pumpQueue();
      return;
    }

    // Use AbortController to remove ended/error/playing listeners on flush so
    // a pooled element can't accumulate stale listeners across rounds (an old
    // listener firing late would mutate isPlayingRef out from under a fresh
    // play and re-pump the queue mid-clip).
    const ac =
      typeof AbortController !== 'undefined' ? new AbortController() : null;
    const listenerOpts: AddEventListenerOptions = ac
      ? { once: true, signal: ac.signal }
      : { once: true };

    isPlayingRef.current = true;
    currentAudioRef.current = audio;
    const myRunId = item.runId;
    let settled = false;
    let started = false;
    let watchdog: ReturnType<typeof setTimeout> | null = null;
    console.info('[VOICE-AUDIT] PLAY ATTEMPT', {
      context: item.context,
      kind: item.kind,
      pooledHit,
      queueLenBefore,
      queueLenAfter,
      isPlayingRef: true,
      readyState: audio.readyState,
    });

    const onDone = (reason: string, detail?: unknown) => {
      if (settled) return;
      settled = true;
      if (watchdog) { clearTimeout(watchdog); watchdog = null; }
      if (ac) {
        try { ac.abort(); } catch {}
      }
      if (reason === 'ended') {
        console.info('[VOICE-AUDIT] PLAY ENDED', { context: item.context, started });
      } else {
        console.warn('[VOICE-AUDIT] PLAY ENDED EARLY', {
          context: item.context, reason, started,
          mediaError: (audio as any).error?.code,
          detail,
        });
      }
      if (currentAudioRef.current === audio) currentAudioRef.current = null;
      isPlayingRef.current = false;
      // If a flush happened (runId bumped) while we were playing, don't pump —
      // the flush already cleared the queue and we should stay quiet until the
      // next enqueue.
      if (myRunId !== runIdRef.current) return;
      if (gapTimerRef.current) clearTimeout(gapTimerRef.current);
      gapTimerRef.current = setTimeout(() => {
        gapTimerRef.current = null;
        pumpQueue();
      }, QUEUE_GAP_MS);
    };

    audio.addEventListener('ended', () => onDone('ended'), listenerOpts);
    audio.addEventListener(
      'error',
      () => onDone('error', (audio as any).error),
      listenerOpts,
    );
    audio.addEventListener(
      'playing',
      () => {
        started = true;
        console.info('[VOICE-AUDIT] PLAY STARTED', {
          context: item.context,
          duration: audio.duration,
        });
      },
      listenerOpts,
    );

    try {
      const p = audio.play();
      if (p && typeof p.then === 'function') {
        p.then(
          () => {
            console.info('[VOICE-AUDIT] PLAY RESOLVED', {
              context: item.context, paused: audio.paused, started,
            });
          },
          (err: unknown) => onDone('play-rejected', err),
        );
      }
    } catch (err) {
      onDone('play-threw', err);
      return;
    }

    // Watchdog: if play() resolved but the 'playing' event never fires within
    // 5s, the audio element is wedged (iOS Safari can resolve play() without
    // actually starting playback after several elements have been created).
    // Drop the pooled element so the next play creates a fresh one, and pump
    // the next item so the queue doesn't deadlock.
    watchdog = setTimeout(() => {
      if (settled || started) return;
      console.warn('[VOICE-AUDIT] PLAY STALLED — no `playing` event in 5s', {
        context: item.context,
        readyState: audio.readyState,
        networkState: audio.networkState,
        paused: audio.paused,
        currentTime: audio.currentTime,
        mediaError: (audio as any).error?.code,
      });
      // Evict the wedged element from the pool so the next attempt for this
      // URL/cue creates a fresh HTMLAudioElement.
      if (audioPool[poolKey] === audio) {
        try { audio.pause(); } catch {}
        delete audioPool[poolKey];
      }
      onDone('play-stalled');
    }, 5000);
  }, [isMuted, ttsDisabled, logSpeechSuppressed]);

  // ── Queue API ───────────────────────────────────────────────────────
  const enqueueCue = useCallback(
    (key: CueKey, context: string = '') => {
      if (isMuted || ttsDisabled) return;
      if (Platform.OS !== 'web' || typeof window === 'undefined') return;
      queueRef.current.push({ kind: 'cue', key, context, runId: runIdRef.current });
      pumpQueue();
    },
    [isMuted, ttsDisabled, pumpQueue],
  );

  // Enqueue a dynamic voice URL (OpenAI movement clips). Empty URL logs the
  // gap and does not enqueue (nothing would play anyway).
  const enqueueVoice = useCallback(
    (url: string, context: string) => {
      if (isMuted || ttsDisabled) {
        console.warn('[VOICE-AUDIT] enqueueVoice dropped — muted/ttsDisabled', { context, isMuted, ttsDisabled });
        return;
      }
      if (Platform.OS !== 'web' || typeof window === 'undefined') return;
      if (!url) {
        console.warn('[VOICE-AUDIT] enqueueVoice dropped — empty url', { context });
        logSpeechSuppressed(context, '');
        return;
      }
      console.info('[VOICE-AUDIT] enqueueVoice queued', { context, urlPreview: url.slice(0, 80) });
      queueRef.current.push({ kind: 'voice', url, context, runId: runIdRef.current });
      pumpQueue();
    },
    [isMuted, ttsDisabled, logSpeechSuppressed, pumpQueue],
  );

  // Flush everything: bump runId so in-flight play()s drop their post-ended
  // pump, stop the currently playing audio, clear pending items, cancel the
  // inter-clip gap timer. Called from Skip (resetSpoken=true) so the new skip
  // target's cues fire fresh, and from Pause (resetSpoken=false) where we
  // keep track of what was already announced so cues don't double up on
  // resume.
  const stopAllAudio = useCallback((resetSpoken = true) => {
    runIdRef.current += 1;
    queueRef.current.length = 0;
    if (gapTimerRef.current) {
      clearTimeout(gapTimerRef.current);
      gapTimerRef.current = null;
    }
    try {
      if (currentAudioRef.current) {
        currentAudioRef.current.pause();
        try { currentAudioRef.current.currentTime = 0; } catch {}
      }
      if (Platform.OS === 'web' && typeof window !== 'undefined') {
        window.speechSynthesis?.cancel();
      } else {
        Speech.stop();
      }
    } catch {}
    currentAudioRef.current = null;
    isPlayingRef.current = false;
    if (resetSpoken) {
      countdownSpokenRef.current = -1;
      halfwaySpokenRef.current = false;
      combinedWorkRestFiredIndexRef.current = -1;
      combinedRestGoFiredIndexRef.current = -1;
    }
  }, []);

  // On web, we always have audio (our own files). On native, check expo-speech.
  useEffect(() => {
    if (Platform.OS === 'web') {
      setIsTTSAvailable(typeof window !== 'undefined');
    } else {
      Speech.getAvailableVoicesAsync()
        .then((voices) => setIsTTSAvailable(voices.length > 0))
        .catch(() => setIsTTSAvailable(false));
    }
  }, []);

  // ── Special block announcements ────────────────────────────────────
  useEffect(() => {
    if (isPaused) return;
    if (!current) return;
    const stepType = current.stepType;

    // Intro block
    if (phase === 'intro' || (phase === 'work' && stepType === 'intro')) {
      const key = `intro_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('lets_get_started', key);
      }
      return;
    }

    // Outro block
    if (phase === 'outro' || (phase === 'work' && stepType === 'outro')) {
      const key = `outro_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('workout_complete_long', key);
      }
      return;
    }

    // Demo block. Until there's an OpenAI/MP3 cue for "Here's what's coming
    // up" + the demo movement names, we stay silent (visual list is shown on
    // screen). Device speech would read the list aloud in the robotic voice,
    // which clashes with the OpenAI-voiced rest of the player.
    if (phase === 'demo' || (phase === 'work' && stepType === 'demo')) {
      const key = `demo_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        const movements = current.demoMovements || [];
        const names = movements.map((m: any) => m.name).join(', then ');
        logSpeechSuppressed(
          `demo_block_${currentIndex}`,
          names ? `Here's what's coming up: ${names}` : "Here's what's coming up",
        );
      }
      return;
    }

    // Transition block. Coach-custom prose doesn't have an OpenAI clip per
    // transition yet; stay silent and log so we can see which transitions
    // need voice coverage. The `get_ready` MP3 is played for empty-instruction
    // transitions since that's a safe static cue.
    if (phase === 'transition' || (phase === 'work' && stepType === 'transition')) {
      const key = `transition_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        const instruction = current.instructionText || current.description || '';
        if (instruction) {
          logSpeechSuppressed(`transition_${currentIndex}`, instruction);
        } else {
          enqueueCue('get_ready', key);
        }
      }
      return;
    }

    // Water Break block
    if (phase === 'waterBreak' || (phase === 'work' && stepType === 'waterBreak')) {
      const key = `waterBreak_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('water_break', key);
      }
      return;
    }
  }, [phase, current?.stepType, currentIndex, logSpeechSuppressed, enqueueCue, isPaused]);

  // ── Welcome message on first work phase ─────────────────────────────
  useEffect(() => {
    if (isPaused) return;
    if (phase === 'work' && currentIndex === 0 && !welcomeSpokenRef.current) {
      if (current?.stepType === 'exercise') {
        welcomeSpokenRef.current = true;
        enqueueCue('workout_starting', 'welcome');
      }
    }
  }, [phase, currentIndex, current?.stepType, enqueueCue, isPaused]);

  // ── Exercise movement announcements ────────────────────────────────
  // Extracted ahead of the effect so the dep array references a flat
  // identifier (eslint react-hooks rule rejects complex expressions there).
  const nextNextUpVoiceUrl = (next as any)?.nextUpVoiceUrl as string | undefined;
  useEffect(() => {
    if (isPaused) return;
    if (!current || current.stepType !== 'exercise') return;

    if (phase === 'work') {
      const key = `work_${currentIndex}_${current.name}`;
      if (lastSpokenRef.current !== key) {
        const previousKey = lastSpokenRef.current;
        lastSpokenRef.current = key;
        halfwaySpokenRef.current = false;
        countdownSpokenRef.current = -1;
        restCountdownSpokenRef.current = -1;
        // The "Next up, {name}" line normally plays on the rest screen leading
        // into this movement, so work-start stays silent and the spoken "Go"
        // closes the rest countdown. But if we arrived at work WITHOUT a
        // preceding rest announcement (very first movement with no prep, or a
        // movement with restAfter=0 chained straight into the next), nothing
        // would have spoken the name — so enqueue it here as a fallback only
        // in that case. The queue serializes it behind the welcome cue (on
        // index 0) so no clipping.
        const announcedByPriorRest = previousKey === `rest_${currentIndex - 1}`
          || previousKey === `rest_${currentIndex}`;
        if (!announcedByPriorRest) {
          const voiceUrl = current.voiceUrl;
          enqueueVoice(voiceUrl || '', `work_${currentIndex}_${current.name}`);
        }
      }
    } else if (phase === 'rest') {
      const nextName = next?.name;
      const key = `rest_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        countdownSpokenRef.current = -1;
        restCountdownSpokenRef.current = -1;
        pendingNextUpPhraseRef.current = null;
        // Synthetic "Get Ready" prep-rest step (movementIndex === -1) plays BEFORE
        // the first movement of a block.
        const isPrepRest = current?.movementIndex === -1;
        // If the work→rest combined clip already played, it included
        // "Rest. Next up, {name}." — do not also enqueue the standalone
        // next-up phrase.
        const combinedWorkRestFired = combinedWorkRestFiredIndexRef.current === currentIndex;
        if (combinedWorkRestFired) {
          console.info(
            '[VOICE-AUDIT] rest entry — suppressing standalone next-up phrase (combined work→rest→next-up clip already fired)',
            { currentIndex, nextName },
          );
        } else if (nextName) {
          // Queue order: [rest (enqueued at end of previous work phase)] →
          // [combined "Next up, {name}." phrase clip]. One OpenAI clip with
          // style instructions replaces the old next_up MP3 + standalone
          // movement-name voiceUrl pair so the cue sounds like one coherent
          // sentence with no audible seam. Pre-warm runs at workout-open;
          // the URL arrives on the FlatMovement as nextUpVoiceUrl.
          const nextMovementId = (next as any)?.movementId || '';
          const logContext = `rest_next_up_${nextName}`;
          const phraseUrl = nextNextUpVoiceUrl || '';
          console.info('[VOICE-AUDIT] rest entry — combined next-up phrase state', {
            currentIndex,
            nextName,
            nextMovementId: nextMovementId || '(MISSING)',
            phraseUrlPresent: !!phraseUrl,
            phraseUrlPreview: phraseUrl ? phraseUrl.slice(0, 80) : '',
          });
          if (phraseUrl) {
            enqueueVoice(phraseUrl, logContext);
          } else {
            // Phrase not ready yet (first encounter, generation still in
            // flight). Stay silent for this rest per product decision —
            // device speech is off-brand and the old two-clip fallback is
            // gone. Late-arrival effect picks it up if it shows up before
            // the rest countdown window.
            pendingNextUpPhraseRef.current = {
              restKey: key,
              movementId: nextMovementId,
              name: nextName,
              context: logContext,
            };
            console.warn(
              '[VOICE-AUDIT] next-up phrase not ready — late-arrival watcher armed',
              { movementId: nextMovementId || '(MISSING)', name: nextName, context: logContext },
            );
          }
        } else if (!isPrepRest) {
          enqueueCue('rest_now', `rest_${currentIndex}_rest_now`);
        }
      }
    } else if (phase === 'swap') {
      const key = `swap_${currentIndex}`;
      if (lastSpokenRef.current !== key) {
        lastSpokenRef.current = key;
        enqueueCue('switch_sides', key);
      }
    } else if (phase === 'ready') {
      lastSpokenRef.current = '';
      welcomeSpokenRef.current = false;
      halfwaySpokenRef.current = false;
      countdownSpokenRef.current = -1;
    }
  }, [phase, current?.name, current?.stepType, current?.voiceUrl, currentIndex, next?.name, nextNextUpVoiceUrl, enqueueCue, enqueueVoice, isPaused]);

  // ── Halfway announcement (exercise only) ───────────────────────────
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'work' || !current || current.stepType !== 'exercise') return;
    if (currentDuration <= 6) return;
    const halfway = Math.floor(currentDuration / 2);
    if (timeLeft === halfway && !halfwaySpokenRef.current) {
      halfwaySpokenRef.current = true;
      enqueueCue('halfway', `halfway_${currentIndex}`);
    }
  }, [phase, timeLeft, currentDuration, current, enqueueCue, isPaused, currentIndex]);

  // ── Countdown voice (exercise only) ────────────────────────────────
  // Trigger timing rationale (Devin reported the combined clip felt ~1s late):
  //   The combined clip's SSML opens with a 200ms <break/> lead and ~700ms
  //   between digits (matched to the visual 1s tick). On iOS Safari the first
  //   `play()` for a fresh URL adds another ~300–800ms of decode + start
  //   latency. Triggering at `displayed===3` (timeLeft hits 3) made the audio
  //   "3" word land ~600–1200ms after the visual "3" appeared — exactly the
  //   "about a second late" Devin heard. Firing one tick earlier (timeLeft
  //   hits 4) absorbs that startup latency so the audio digits land in sync.
  //
  // At timeLeft === 4 (combined clip path):
  //   Prefer the combined "3, 2, 1. Rest. Next up, {name}." Voicemaker clip.
  //   Fires once per movement index (gated by combinedWorkRestFiredIndexRef).
  //   Falls through to displayed===3 when the combined URL isn't ready, the
  //   current movement has swapSides (next is swap not rest), the next step
  //   isn't a plain exercise, or it's the last movement.
  // At timeLeft === 3 (standalone fallback):
  //   Enqueue countdown_3 ONLY when the combined clip didn't fire at
  //   displayed===4 (we'd double up otherwise).
  // At timeLeft === 0:
  //   If the combined clip fired, the `rest` word is already in that clip —
  //   skip the standalone `rest` cue. Otherwise enqueue `rest`. Last movement
  //   always fires `workout_complete` (no transition clip applies).
  const nextWorkRestNextUpVoiceUrl = (next as any)?.workRestNextUpVoiceUrl as string | undefined;
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'work' || !current || current.stepType !== 'exercise') return;
    if (currentDuration <= 0) return;

    const displayed = Math.max(0, Math.ceil(timeLeft));
    // displayed===4 is the EARLIEST tick where we can fire the combined clip
    // and still have ~1s of head start. Guard with countdownSpokenRef so it
    // only fires once per countdown window. Skip when the work duration is
    // <=4s (the visual countdown won't have a clean "4,3,2,1" sequence and we
    // shouldn't pre-empt the cue at workout-start).
    if (displayed === 4 && timeLeft > 0 && currentDuration > 4 && countdownSpokenRef.current < 0) {
      const isLastMovement = currentIndex >= total - 1;
      const nextIsExercise = !!next
        && (!(next as any).stepType || (next as any).stepType === 'exercise');
      const hasSwapSidesOngoing = !!current?.swapSides;
      const combinedUrl = nextWorkRestNextUpVoiceUrl || '';
      if (!isLastMovement && nextIsExercise && !hasSwapSidesOngoing && combinedUrl) {
        countdownSpokenRef.current = 4;
        console.info(
          '[VOICE-AUDIT] work→rest combined clip — enqueueing one-breath transition (early trigger)',
          { currentIndex, nextName: (next as any)?.name, urlPreview: combinedUrl.slice(0, 80), timeLeft },
        );
        enqueueVoice(combinedUrl, `work_rest_next_combined_${currentIndex}`);
        combinedWorkRestFiredIndexRef.current = currentIndex;
      }
      // If we didn't fire the combined clip, leave countdownSpokenRef untouched
      // so the displayed===3 branch below still fires the standalone countdown.
    }
    if (displayed === 3 && timeLeft > 0 && countdownSpokenRef.current !== 3 && countdownSpokenRef.current !== 4) {
      countdownSpokenRef.current = 3;
      // Combined clip didn't fire at displayed===4 (no URL, swap-sides, last
      // movement, or special-block next) — fall back to the static countdown.
      enqueueCue('countdown_3', `work_countdown_${currentIndex}`);
    } else if (displayed === 3 && timeLeft > 0 && countdownSpokenRef.current === 4) {
      // Combined clip already fired one second ago — mark the 3-spoken slot
      // so the timeLeft<=0 branch below correctly identifies that the "3"
      // window has passed without re-entering this branch.
      countdownSpokenRef.current = 3;
    } else if (timeLeft <= 0 && countdownSpokenRef.current !== 0) {
      countdownSpokenRef.current = 0;
      const isLastMovement = currentIndex >= total - 1;
      // End-of-workout audio rule: see header comment for the full table.
      const nextIsSpecial = next && (next as any).stepType && (next as any).stepType !== 'exercise';
      const combinedFired = combinedWorkRestFiredIndexRef.current === currentIndex;
      if (isLastMovement) {
        enqueueCue('workout_complete', `work_end_${currentIndex}`);
      } else if (!nextIsSpecial && !combinedFired) {
        enqueueCue('rest', `work_end_${currentIndex}`);
      }
    }
  }, [phase, timeLeft, current, currentDuration, currentIndex, total, next, nextWorkRestNextUpVoiceUrl, enqueueCue, enqueueVoice, isPaused]);

  // ── Rest countdown voice (rest → next exercise only) ───────────────
  // Spoken "3, 2, 1. Go." for the rest-exit transition. Same lateness fix as
  // the work→rest path: trigger the combined clip at displayed===4 (one tick
  // earlier) so the SSML lead break and iOS Safari decode latency are
  // absorbed before the audio "3" word needs to land.
  //   At timeLeft === 4: prefer the combined "3, 2, 1. Go." Voicemaker clip.
  //     Skipped when the rest duration is <=4s (no clean countdown window).
  //   At timeLeft === 3: standalone countdown_3 fallback when the combined
  //     clip didn't fire at the early trigger.
  //   At timeLeft === 0: suppress the standalone `go` cue when the combined
  //     clip fired (it already said "Go"). Still suppresses when next isn't
  //     an exercise (demo/transition/waterBreak handle their own cue).
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'rest') return;

    const displayed = Math.max(0, Math.ceil(timeLeft));
    // Note: `currentDuration` here is the just-finished work duration, not the
    // rest duration — so we can't use it as a "rest is long enough" gate. Just
    // require timeLeft > 0 and rely on the spoken-ref for once-per-phase guard.
    if (displayed === 4 && timeLeft > 0 && restCountdownSpokenRef.current < 0) {
      const nextIsExercise = !!next
        && (!(next as any).stepType || (next as any).stepType === 'exercise');
      if (nextIsExercise && restGoVoiceUrl) {
        restCountdownSpokenRef.current = 4;
        console.info(
          '[VOICE-AUDIT] rest→go combined clip — enqueueing one-breath transition (early trigger)',
          { currentIndex, urlPreview: restGoVoiceUrl.slice(0, 80), timeLeft },
        );
        enqueueVoice(restGoVoiceUrl, `rest_go_combined_${currentIndex}`);
        combinedRestGoFiredIndexRef.current = currentIndex;
      }
    }
    if (displayed === 3 && timeLeft > 0 && restCountdownSpokenRef.current !== 3 && restCountdownSpokenRef.current !== 4) {
      restCountdownSpokenRef.current = 3;
      enqueueCue('countdown_3', `rest_countdown_${currentIndex}`);
    } else if (displayed === 3 && timeLeft > 0 && restCountdownSpokenRef.current === 4) {
      restCountdownSpokenRef.current = 3;
    } else if (timeLeft <= 0 && restCountdownSpokenRef.current !== 0) {
      restCountdownSpokenRef.current = 0;
      const nextIsExercise = next
        && (!(next as any).stepType || (next as any).stepType === 'exercise');
      const combinedFired = combinedRestGoFiredIndexRef.current === currentIndex;
      if (nextIsExercise && !combinedFired) {
        enqueueCue('go', `rest_end_${currentIndex}`);
      } else if (!nextIsExercise) {
        console.warn(
          '[useWorkoutTTS] rest→? "Go" suppressed (next is not a plain exercise)',
          {
            hasNext: !!next,
            nextStepType: (next as any)?.stepType,
            nextName: (next as any)?.name,
            currentIndex,
            timeLeft,
          },
        );
      }
    }
  }, [phase, timeLeft, currentDuration, next, currentIndex, restGoVoiceUrl, enqueueCue, enqueueVoice, isPaused]);

  // ── Late-arriving combined "Next up, {name}." phrase clip ────────
  // Pre-warm normally has the phrase URL injected before rest-entry, but
  // first-ever encounter of a phrase has to wait on OpenAI (~1-3s). When
  // useNextUpPhrases pushes the URL into state mid-rest, this watcher
  // enqueues it — provided we still have enough time before the rest
  // countdown that the clip can finish without clipping "3, 2, 1, Go".
  useEffect(() => {
    if (isPaused) return;
    if (phase !== 'rest') return;
    const pending = pendingNextUpPhraseRef.current;
    if (!pending) return;
    // Only the movement we were waiting on — never play a stale name.
    const nextMovementId = (next as any)?.movementId || '';
    if (pending.movementId && nextMovementId && pending.movementId !== nextMovementId) {
      console.warn('[VOICE-AUDIT] late-arrival: movementId mismatch — clearing pending', {
        pendingId: pending.movementId, nextMovementId,
      });
      pendingNextUpPhraseRef.current = null;
      return;
    }
    const phraseUrl = (next as any)?.nextUpVoiceUrl || '';
    if (!phraseUrl) return;
    // Don't enqueue a phrase clip into the rest→work countdown window.
    if (timeLeft <= 3.5) {
      console.warn(
        '[VOICE-AUDIT] late next-up phrase arrived inside rest countdown — skipping',
        { name: pending.name, timeLeft },
      );
      pendingNextUpPhraseRef.current = null;
      return;
    }
    pendingNextUpPhraseRef.current = null;
    console.info(
      '[VOICE-AUDIT] late next-up phrase arrived — enqueuing',
      { name: pending.name, timeLeft, urlPreview: phraseUrl.slice(0, 80) },
    );
    enqueueVoice(phraseUrl, `${pending.context}_late`);
  }, [phase, timeLeft, next, enqueueVoice, isPaused]);

  // ── Pause → silence any audio in flight ─────────────────────────────
  useEffect(() => {
    if (!isPaused) return;
    stopAllAudio(false);
  }, [isPaused, stopAllAudio]);

  // ── Mute → silence any audio in flight ─────────────────────────────
  // The `isMuted || ttsDisabled` guards in enqueue/pump prevent *new* cues
  // from starting, but the currently playing clip and anything already
  // queued need to be stopped / dropped immediately on mute.
  useEffect(() => {
    if (!isMuted) return;
    stopAllAudio(false);
  }, [isMuted, stopAllAudio]);

  // ── Cleanup ─────────────────────────────────────────────────────────
  useEffect(() => {
    return () => {
      runIdRef.current += 1;
      queueRef.current.length = 0;
      if (gapTimerRef.current) {
        clearTimeout(gapTimerRef.current);
        gapTimerRef.current = null;
      }
      try {
        if (currentAudioRef.current) {
          currentAudioRef.current.pause();
          currentAudioRef.current = null;
        }
        if (Platform.OS === 'web' && typeof window !== 'undefined') {
          window.speechSynthesis?.cancel();
        } else {
          Speech.stop();
        }
      } catch {}
    };
  }, []);

  return { isTTSAvailable, stopAllAudio };
}
