import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { execFileSync } from 'child_process';
import type { DocumentReference, Firestore } from 'firebase-admin/firestore';
import {
  buildReadyRenderedVideoMeta,
  buildRenderStorageLocation,
  decodeSegmentId,
  flattenWorkout,
  hashRenderSource,
  isCurrentRenderRequest,
  Segment,
} from '../renderContract';
import { buildSegmentArgs, generateAss } from '../renderFfmpeg';
import { parseRenderServiceTarget } from '../renderServiceTarget';
import {
  claimRenderRequest,
  commitFailedRenderIfCurrent,
  commitReadyRenderIfCurrent,
} from '../renderState';
import {
  lookupBlockAtVideoTime,
  PersistedRenderedVideoMeta as PlayerPersistedMeta,
  ResolvedRenderedVideoMeta as PlayerResolvedMeta,
  validateMeta,
  videoTimeForBlock,
} from '../../../apps/goarrive/utils/renderedVideoOffsetMap';

const WORKOUT_ID = 'workout/contract #1';
const WORKOUT = {
  introVideoUrl: 'https://cdn.example.com/intro.mp4',
  blocks: [
    {
      type: 'Circuit',
      movements: [
        {
          id: 'movement-a',
          name: 'Squat',
          videoUrl: 'https://cdn.example.com/squat.mp4',
          duration: 30,
          restAfter: 15,
        },
      ],
    },
    {
      type: 'Circuit',
      movements: [
        {
          id: 'movement-b',
          name: 'Plank',
          thumbnailUrl: 'https://cdn.example.com/plank.jpg',
          duration: 45,
        },
      ],
      restDurationSeconds: 20,
    },
  ],
  outroVideoUrl: 'https://cdn.example.com/outro.mp4',
};

const EMITTER_PLAYER_FIXTURE = JSON.parse(
  fs.readFileSync(
    path.resolve(__dirname, '../../../contracts/rendered-video/emitter-player-contract-v1.json'),
    'utf8',
  ),
) as {
  bucketName: string;
  workoutId: string;
  identity: { version: number; sourceHash: string };
  workout: Record<string, unknown>;
  omittedSegmentIndexes: number[];
  expected: PlayerPersistedMeta;
};

type JsonRecord = Record<string, unknown>;

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function setPath(target: JsonRecord, dottedPath: string, value: unknown): void {
  const parts = dottedPath.split('.');
  let current = target;
  parts.slice(0, -1).forEach((part) => {
    const existing = current[part];
    if (!existing || typeof existing !== 'object') current[part] = {};
    current = current[part] as JsonRecord;
  });
  current[parts[parts.length - 1]] = value;
}

class FakeFirestore {
  data: JsonRecord;
  writes: JsonRecord[] = [];

  constructor(data: JsonRecord) {
    this.data = clone(data);
  }

  async runTransaction<T>(
    callback: (transaction: {
      get: (ref: unknown) => Promise<{ exists: boolean; data: () => JsonRecord }>;
      update: (ref: unknown, patch: JsonRecord) => void;
    }) => Promise<T>,
  ): Promise<T> {
    return callback({
      get: async () => ({ exists: true, data: () => clone(this.data) }),
      update: (_ref, patch) => {
        this.writes.push(patch);
        Object.entries(patch).forEach(([key, value]) => {
          if (key.includes('.')) setPath(this.data, key, value);
          else this.data[key] = value;
        });
      },
    });
  }
}

const fakeRef = {} as DocumentReference;

function asFirestore(fake: FakeFirestore): Firestore {
  return fake as unknown as Firestore;
}

describe('renderer × merged #263 timeline contract', () => {
  test('shared emitter fixture is generated by the production contract', () => {
    const allSegments = flattenWorkout(
      EMITTER_PLAYER_FIXTURE.workout,
      EMITTER_PLAYER_FIXTURE.workoutId,
    );
    const omitted = new Set(EMITTER_PLAYER_FIXTURE.omittedSegmentIndexes);
    const emittedSegments = allSegments.filter((segment) => !omitted.has(segment.segmentIndex));

    expect(hashRenderSource(EMITTER_PLAYER_FIXTURE.workout)).toBe(
      EMITTER_PLAYER_FIXTURE.identity.sourceHash,
    );
    expect(buildReadyRenderedVideoMeta(
      EMITTER_PLAYER_FIXTURE.bucketName,
      EMITTER_PLAYER_FIXTURE.workoutId,
      EMITTER_PLAYER_FIXTURE.identity,
      emittedSegments,
    )).toEqual(EMITTER_PLAYER_FIXTURE.expected);
  });

  test('segment ids are deterministic, globally unique, reversible, and retain context', () => {
    const first = flattenWorkout(WORKOUT, WORKOUT_ID);
    const second = flattenWorkout(clone(WORKOUT), WORKOUT_ID);
    expect(second.map((segment) => segment.blockId)).toEqual(first.map((segment) => segment.blockId));
    expect(new Set(first.map((segment) => segment.blockId)).size).toBe(first.length);

    const decoded = first.map((segment) => decodeSegmentId(segment.blockId));
    expect(decoded.every(Boolean)).toBe(true);
    expect(decoded).toContainEqual(expect.objectContaining({
      workoutId: WORKOUT_ID,
      parentBlockId: 'block-0',
      blockIndex: 0,
      phase: 'work',
      movementId: 'movement-a',
      movementIndex: 0,
    }));
    expect(decoded).toContainEqual(expect.objectContaining({
      parentBlockId: 'block-0',
      phase: 'movement-rest',
      movementId: 'movement-a',
    }));
  });

  test('same-type blocks without ids cannot collide', () => {
    const segments = flattenWorkout(WORKOUT, WORKOUT_ID);
    const workSegments = segments.filter((segment) => segment.phase === 'work');
    expect(workSegments.map((segment) => segment.parentBlockId)).toEqual(['block-0', 'block-1']);
    expect(workSegments[0].blockId).not.toBe(workSegments[1].blockId);
  });

  test('actual persisted renderer output validates and round-trips without a fake URL', () => {
    const sourceHash = hashRenderSource(WORKOUT);
    const metadata = buildReadyRenderedVideoMeta(
      'bucket.firebasestorage.app',
      WORKOUT_ID,
      { version: 7, sourceHash },
      flattenWorkout(WORKOUT, WORKOUT_ID),
    );
    const playerMeta: PlayerPersistedMeta = metadata;
    const resolvedMeta: PlayerResolvedMeta = {
      ...playerMeta,
      url: 'https://trusted-read.example.test/short-lived-url',
    };

    expect(Object.prototype.hasOwnProperty.call(metadata, 'url')).toBe(false);
    expect(validateMeta(playerMeta)).toEqual([]);
    expect(validateMeta(resolvedMeta)).toEqual([]);
    playerMeta.blocks.forEach((block) => {
      const time = videoTimeForBlock(playerMeta, block.blockId);
      expect(time).toBe(block.startMs);
      expect(lookupBlockAtVideoTime(playerMeta, time!).blockId).toBe(block.blockId);
    });
  });

  test('offsets and duration include only successfully emitted media', () => {
    const allSegments = flattenWorkout(WORKOUT, WORKOUT_ID);
    const omitted = allSegments[2];
    const emitted = allSegments.filter((segment) => segment !== omitted);
    const metadata = buildReadyRenderedVideoMeta(
      'bucket.firebasestorage.app',
      WORKOUT_ID,
      { version: 2, sourceHash: hashRenderSource(WORKOUT) },
      emitted,
    );

    expect(metadata.blocks.map((block) => block.blockId)).not.toContain(omitted.blockId);
    expect(metadata.blocks.map((block) => block.segmentIndex)).toEqual(
      emitted.map((segment) => segment.segmentIndex),
    );
    expect(metadata.blocks.map((block) => block.segmentIndex)).not.toContain(omitted.segmentIndex);
    expect(metadata.blocks.some((block) => block.segmentIndex > omitted.segmentIndex)).toBe(true);
    expect(metadata.durationMs).toBe(
      emitted.reduce((sum, segment) => sum + Math.round(segment.durationSec * 1000), 0),
    );
    expect(validateMeta(metadata)).toEqual([]);
  });
});

describe('durable storage and source identity', () => {
  test('source hash is canonical and changes for every rendered input class', () => {
    expect(hashRenderSource(WORKOUT)).toBe(hashRenderSource(clone(WORKOUT)));
    const changed = clone(WORKOUT) as JsonRecord;
    changed.restDurationSeconds = 99;
    expect(hashRenderSource(changed)).not.toBe(hashRenderSource(WORKOUT));
  });

  test('storage location is immutable, versioned, source-bound, and unsigned', () => {
    const identity = { version: 4, sourceHash: hashRenderSource(WORKOUT) };
    const location = buildRenderStorageLocation(
      'bucket.firebasestorage.app',
      WORKOUT_ID,
      identity,
    );
    expect(location.storagePath).toBe(
      `gs://bucket.firebasestorage.app/rendered-videos/${encodeURIComponent(WORKOUT_ID)}` +
      `/v4/${identity.sourceHash}.mp4`,
    );
    expect(location.storagePath).not.toMatch(/[?&](x-goog-|signature)/i);
  });
});

describe('atomic render state production helpers', () => {
  test('claim assigns one version and source hash atomically; duplicate claim is skipped', async () => {
    const sourceHash = hashRenderSource(WORKOUT);
    const fake = new FakeFirestore({ ...WORKOUT, renderedVideo: { status: 'ready', version: 3 } });
    const first = await claimRenderRequest(asFirestore(fake), fakeRef, sourceHash);
    const second = await claimRenderRequest(asFirestore(fake), fakeRef, sourceHash);
    expect(first).toEqual({ version: 4, sourceHash });
    expect(second).toBeNull();
    expect(fake.data.renderedVideo).toEqual(expect.objectContaining({
      status: 'rendering',
      version: 4,
      sourceHash,
    }));
  });

  test('claim rejects an event whose source was superseded', async () => {
    const fake = new FakeFirestore({ ...WORKOUT, renderedVideo: { status: 'pending', version: 3 } });
    const staleHash = hashRenderSource({ ...WORKOUT, restDurationSeconds: 1 });
    expect(await claimRenderRequest(asFirestore(fake), fakeRef, staleHash)).toBeNull();
    expect(fake.writes).toHaveLength(0);
  });

  test('ready commit requires exact version, metadata hash, and live source hash', async () => {
    const sourceHash = hashRenderSource(WORKOUT);
    const identity = { version: 4, sourceHash };
    const segments = flattenWorkout(WORKOUT, WORKOUT_ID);
    const metadata = buildReadyRenderedVideoMeta(
      'bucket.firebasestorage.app',
      WORKOUT_ID,
      identity,
      segments,
    );
    const fake = new FakeFirestore({ ...WORKOUT, renderedVideo: { status: 'rendering', ...identity } });
    expect(await commitReadyRenderIfCurrent(asFirestore(fake), fakeRef, identity, metadata)).toBe(true);
    expect(fake.data.renderedVideo).toEqual(expect.objectContaining({
      status: 'ready',
      version: 4,
      sourceHash,
      storagePath: metadata.storagePath,
    }));
  });

  test('equal version with a different source hash cannot commit ready state', async () => {
    const sourceHash = hashRenderSource(WORKOUT);
    const identity = { version: 4, sourceHash };
    const metadata = buildReadyRenderedVideoMeta(
      'bucket.firebasestorage.app',
      WORKOUT_ID,
      identity,
      flattenWorkout(WORKOUT, WORKOUT_ID),
    );
    const changedWorkout = { ...WORKOUT, restDurationSeconds: 77 };
    const fake = new FakeFirestore({
      ...changedWorkout,
      renderedVideo: { status: 'rendering', version: 4, sourceHash: hashRenderSource(changedWorkout) },
    });
    expect(await commitReadyRenderIfCurrent(asFirestore(fake), fakeRef, identity, metadata)).toBe(false);
    expect(fake.writes).toHaveLength(0);
  });

  test('an explicit pending rerender cannot be overwritten by terminal writes', async () => {
    const sourceHash = hashRenderSource(WORKOUT);
    const identity = { version: 4, sourceHash };
    const metadata = buildReadyRenderedVideoMeta(
      'bucket.firebasestorage.app',
      WORKOUT_ID,
      identity,
      flattenWorkout(WORKOUT, WORKOUT_ID),
    );
    const pendingReady = new FakeFirestore({
      ...WORKOUT,
      renderedVideo: { status: 'pending', ...identity },
    });
    const pendingFailed = new FakeFirestore({
      ...WORKOUT,
      renderedVideo: { status: 'pending', ...identity },
    });

    expect(
      await commitReadyRenderIfCurrent(asFirestore(pendingReady), fakeRef, identity, metadata),
    ).toBe(false);
    expect(
      await commitFailedRenderIfCurrent(asFirestore(pendingFailed), fakeRef, identity, 'late failure'),
    ).toBe(false);
    expect(pendingReady.data.renderedVideo).toEqual({ status: 'pending', ...identity });
    expect(pendingFailed.data.renderedVideo).toEqual({ status: 'pending', ...identity });
    expect(pendingReady.writes).toHaveLength(0);
    expect(pendingFailed.writes).toHaveLength(0);
  });

  test('ready completion is idempotent and cannot be downgraded by a late duplicate failure', async () => {
    const sourceHash = hashRenderSource(WORKOUT);
    const identity = { version: 4, sourceHash };
    const metadata = buildReadyRenderedVideoMeta(
      'bucket.firebasestorage.app',
      WORKOUT_ID,
      identity,
      flattenWorkout(WORKOUT, WORKOUT_ID),
    );
    const fake = new FakeFirestore({ ...WORKOUT, renderedVideo: metadata });

    expect(
      await commitReadyRenderIfCurrent(asFirestore(fake), fakeRef, identity, metadata),
    ).toBe(true);
    expect(
      await commitFailedRenderIfCurrent(asFirestore(fake), fakeRef, identity, 'late failure'),
    ).toBe(false);
    expect(fake.data.renderedVideo).toEqual(metadata);
    expect(fake.writes).toHaveLength(0);
  });

  test('a failed attempt can still retry and commit ready metadata', async () => {
    const sourceHash = hashRenderSource(WORKOUT);
    const identity = { version: 4, sourceHash };
    const metadata = buildReadyRenderedVideoMeta(
      'bucket.firebasestorage.app',
      WORKOUT_ID,
      identity,
      flattenWorkout(WORKOUT, WORKOUT_ID),
    );
    const fake = new FakeFirestore({
      ...WORKOUT,
      renderedVideo: { status: 'failed', error: 'first attempt failed', ...identity },
    });

    expect(
      await commitReadyRenderIfCurrent(asFirestore(fake), fakeRef, identity, metadata),
    ).toBe(true);
    expect(fake.data.renderedVideo).toEqual(expect.objectContaining({
      status: 'ready',
      version: 4,
      sourceHash,
      storagePath: metadata.storagePath,
    }));
  });

  test('stale failure cannot mark a newer request failed', async () => {
    const sourceHash = hashRenderSource(WORKOUT);
    const staleIdentity = { version: 4, sourceHash };
    const newerIdentity = { version: 5, sourceHash };
    const fake = new FakeFirestore({
      ...WORKOUT,
      renderedVideo: { status: 'rendering', ...newerIdentity },
    });
    expect(
      await commitFailedRenderIfCurrent(asFirestore(fake), fakeRef, staleIdentity, 'old failure'),
    ).toBe(false);
    expect(fake.writes).toHaveLength(0);
  });

  test('current failure is committed and source changes invalidate the request', async () => {
    const sourceHash = hashRenderSource(WORKOUT);
    const identity = { version: 4, sourceHash };
    const fake = new FakeFirestore({ ...WORKOUT, renderedVideo: { status: 'rendering', ...identity } });
    expect(isCurrentRenderRequest(fake.data, identity)).toBe(true);
    expect(
      await commitFailedRenderIfCurrent(asFirestore(fake), fakeRef, identity, 'render failed'),
    ).toBe(true);
    expect(fake.data.renderedVideo).toEqual(expect.objectContaining({
      status: 'failed',
      version: 4,
      sourceHash,
      error: 'render failed',
    }));
  });
});

describe('private Cloud Run service target', () => {
  test('uses request path but service origin as OIDC audience', () => {
    expect(parseRenderServiceTarget('https://render-abc-uc.a.run.app/render/')).toEqual({
      targetUrl: 'https://render-abc-uc.a.run.app/render',
      audience: 'https://render-abc-uc.a.run.app',
    });
  });

  test.each([
    undefined,
    'http://render-abc-uc.a.run.app',
    'https://PLACEHOLDER.run.app/render',
    'https://example.com/render',
    'https://render-abc-uc.a.run.app:444/render',
    'https://render-abc-uc.a.run.app/render?token=nope',
  ])('rejects unsafe service target %p', (target) => {
    expect(() => parseRenderServiceTarget(target)).toThrow();
  });
});

describe('FFmpeg timeline parity', () => {
  test('mixed video and rest segments keep stream timing and metadata aligned', () => {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const ffmpegBin = require('ffmpeg-static') as string | null;
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const ffprobeBin = (require('ffprobe-static') as { path: string }).path;
    if (!ffmpegBin) throw new Error('ffmpeg-static does not support this platform');

    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'goarrive-render-timing-'));
    try {
      const inputPath = path.join(tmpDir, 'source-24fps.mp4');
      const videoAssPath = path.join(tmpDir, 'video.ass');
      const restAssPath = path.join(tmpDir, 'rest.ass');
      const videoOutPath = path.join(tmpDir, 'video.mp4');
      const restOutPath = path.join(tmpDir, 'rest.mp4');
      const concatPath = path.join(tmpDir, 'concat.txt');
      const joinedPath = path.join(tmpDir, 'joined.mp4');

      execFileSync(ffmpegBin, [
        '-hide_banner', '-loglevel', 'error', '-y',
        '-f', 'lavfi', '-i', 'testsrc2=size=320x180:rate=24:duration=1',
        '-c:v', 'libx264', '-pix_fmt', 'yuv420p', inputPath,
      ], { stdio: 'pipe', timeout: 60_000 });

      const workoutId = 'ffmpeg-timeline-contract';
      const workout = {
        blocks: [{
          id: 'mixed-block',
          type: 'Circuit',
          movements: [
            {
              id: 'video-segment',
              name: 'Video',
              videoUrl: 'https://media.example.test/source.mp4',
              duration: 2,
            },
            { id: 'rest-segment', name: 'Rest', duration: 2 },
          ],
        }],
      };
      const segments = flattenWorkout(workout, workoutId);
      expect(segments.map((segment) => segment.type)).toEqual(['video', 'rest']);
      segments[0]._localPath = inputPath;

      fs.writeFileSync(videoAssPath, generateAss(2, '00:04', 'video', 'Video'));
      fs.writeFileSync(restAssPath, generateAss(2, '00:04', 'rest', 'Rest'));
      execFileSync(
        ffmpegBin,
        buildSegmentArgs(segments[0], path.basename(videoAssPath), videoOutPath),
        { cwd: tmpDir, stdio: 'pipe', timeout: 120_000 },
      );
      execFileSync(
        ffmpegBin,
        buildSegmentArgs(segments[1], path.basename(restAssPath), restOutPath),
        { cwd: tmpDir, stdio: 'pipe', timeout: 120_000 },
      );

      const concatEntries = [videoOutPath, restOutPath]
        .map((filePath) => `file '${filePath.replace(/\\/g, '/')}'`)
        .join('\n');
      fs.writeFileSync(concatPath, concatEntries);
      execFileSync(ffmpegBin, [
        '-hide_banner', '-loglevel', 'error', '-y',
        '-f', 'concat', '-safe', '0', '-i', concatPath,
        '-c', 'copy', joinedPath,
      ], { stdio: 'pipe', timeout: 60_000 });

      const probe = (filePath: string): {
        streams: Array<{ r_frame_rate: string; time_base: string; nb_read_frames: string }>;
        format: { duration: string };
      } => JSON.parse(execFileSync(ffprobeBin, [
        '-v', 'error', '-select_streams', 'v:0', '-count_frames',
        '-show_entries', 'stream=r_frame_rate,time_base,nb_read_frames:format=duration',
        '-of', 'json', filePath,
      ], { encoding: 'utf8', timeout: 60_000 }));

      const videoProbe = probe(videoOutPath);
      const restProbe = probe(restOutPath);
      const joinedProbe = probe(joinedPath);
      expect(videoProbe.streams[0]).toEqual(expect.objectContaining({
        r_frame_rate: '30/1',
        time_base: '1/30000',
      }));
      expect(restProbe.streams[0]).toEqual(expect.objectContaining({
        r_frame_rate: '30/1',
        time_base: '1/30000',
      }));

      const metadata = buildReadyRenderedVideoMeta(
        'bucket.firebasestorage.app',
        workoutId,
        { version: 1, sourceHash: hashRenderSource(workout) },
        segments,
      );
      const artifactDurationMs = Number(joinedProbe.format.duration) * 1000;
      expect(metadata.blocks.map(({ startMs, endMs }) => ({ startMs, endMs }))).toEqual([
        { startMs: 0, endMs: 2000 },
        { startMs: 2000, endMs: 4000 },
      ]);
      expect(metadata.durationMs).toBe(4000);
      expect(Math.abs(artifactDurationMs - metadata.durationMs)).toBeLessThanOrEqual(50);
      expect(Number(joinedProbe.streams[0].nb_read_frames)).toBe(120);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  }, 180_000);
});

describe('deploy build contract', () => {
  test('deploy compilation excludes tests and production source stays functions-local', () => {
    const functionsRoot = path.resolve(__dirname, '..', '..');
    const tsconfig = JSON.parse(fs.readFileSync(path.join(functionsRoot, 'tsconfig.json'), 'utf8'));
    const renderJobSource = fs.readFileSync(path.join(functionsRoot, 'src', 'renderJob.ts'), 'utf8');
    const dockerfile = fs.readFileSync(
      path.resolve(functionsRoot, '..', 'docker', 'renderWorkoutVideo.Dockerfile'),
      'utf8',
    );
    const runbook = fs.readFileSync(
      path.resolve(functionsRoot, '..', 'docs', 'render-workout-video-service.md'),
      'utf8',
    );

    expect(tsconfig.exclude).toContain('src/**/__tests__/**');
    expect(renderJobSource).not.toContain("from '../../apps/");
    expect(renderJobSource).toContain("from './renderContract'");
    expect(renderJobSource).toContain('if (require.main === module)');
    expect(renderJobSource).not.toContain('getSignedUrl');
    expect(dockerfile).toContain('rm -rf lib && npm run build && test -f lib/renderJob.js');
    expect(dockerfile).toContain('CMD ["node", "lib/renderJob.js"]');
    expect(runbook).toContain('RENDER_SERVICE_URL');
    expect(runbook).toContain('roles/run.invoker');
    expect(runbook).toContain('roles/cloudtasks.enqueuer');
    expect(runbook).toContain('roles/iam.serviceAccountUser');
    expect(runbook).not.toContain('RENDER_JOB_URL');
  });
});

// Compile-time assertion: production metadata is directly consumable by #263.
const _playerContract: PlayerPersistedMeta = buildReadyRenderedVideoMeta(
  'bucket.firebasestorage.app',
  WORKOUT_ID,
  { version: 1, sourceHash: hashRenderSource(WORKOUT) },
  flattenWorkout(WORKOUT, WORKOUT_ID) as Segment[],
);
void _playerContract;
