import { describe, expect, it } from "bun:test";
import { createFixture, goalTotal, type DemoState } from "../src/demo/model";
import { reducer } from "../src/demo/store";
import { hasShareableSnapshot, togetherOutcome, type TogetherResult } from "../src/demo/together";

const confirm = (s: DemoState, id: string, amount: number, lost = false, movementKey: "squats" | "pushUps" = "squats") => reducer(reducer(s, { type: "submit", attemptId: id, communityId: "oak", goalId: "oak-500", movementKey, amount, lost }), { type: "resolve", attemptId: id });

describe("TOGETHER-COMPLETION-NORTHSTAR-1", () => {
  it("confirmation stores exact immutable boundary facts", () => { const s=confirm(createFixture(),"fresh",20); expect(s.attempt).toMatchObject({ stage:"confirmed", receiptBefore:241, receiptAfter:261, receiptTarget:500, receiptStatus:"open", crossedTarget:false }); expect(goalTotal(s,"oak-500")).toBe(261); });
  it("crossing truth is independent from presentation eligibility", () => { const base=createFixture(), near={...base, scenario:{kind:"near" as const,communityId:"oak",goalId:"oak-500",sampleTotal:490}}; const s=confirm(near,"cross",20); expect(s.attempt).toMatchObject({receiptBefore:490,receiptAfter:510,receiptTarget:500,crossedTarget:true}); expect(togetherOutcome(true,490,510,500,true).headline).toBe("WE did it. Together."); expect(togetherOutcome(true,490,510,500,false).headline).toBe("WE did it. Together."); });
  it("already reached never claims a crossing, closer, or fresh motion", () => { const o=togetherOutcome(false,515,535,500,true); expect(o).toMatchObject({ crossed:false, animate:false, headline:"Your contribution is recorded." }); });
  it("only genuine fresh ordinary and crossing outcomes animate", () => { expect(togetherOutcome(false,241,261,500,true).animate).toBe(true); expect(togetherOutcome(true,490,510,500,true).animate).toBe(true); expect(togetherOutcome(false,241,261,500,false).animate).toBe(false); expect(togetherOutcome(true,490,510,500,false).animate).toBe(false); });
  it("lost-reply reconciliation keeps its boundary snapshot without presentation authority", () => { let base=createFixture(); base={...base,goals:{...base.goals,"oak-500":{...base.goals["oak-500"]!,movements:["squats","pushUps"]}}}; let s=confirm(base,"lost",12,true,"pushUps"); expect(s.attempt).toMatchObject({stage:"unknown",receiptBefore:241,receiptAfter:253}); s=reducer(s,{type:"reconcile",attemptId:"lost"}); expect(s.attempt).toMatchObject({stage:"confirmed",movementKey:"pushUps",amount:12,receiptBefore:241,receiptAfter:253}); expect("confirmedFresh" in (s.attempt ?? {})).toBe(false); });
  it("repeated resolve does not duplicate or create presentation state", () => { let s=confirm(createFixture(),"once",10); const n=s.contributions.length; s=reducer(s,{type:"resolve",attemptId:"once"}); expect(s.contributions).toHaveLength(n); expect("confirmedFresh" in (s.attempt ?? {})).toBe(false); });
  it("confirmation boundary can differ from submit-time aggregate", () => { let s=createFixture(); s=reducer(s,{type:"submit",attemptId:"boundary",communityId:"oak",goalId:"oak-500",amount:20,lost:false}); s={...s,contributions:[...s.contributions,{id:"between",attemptId:"between",memberId:"jordan",communityId:"oak",goalId:"oak-500",amount:7,at:Date.now(),source:"demo"}]}; s=reducer(s,{type:"resolve",attemptId:"boundary"}); expect(s.attempt).toMatchObject({receiptBefore:248,receiptAfter:268}); });
  it("later shared changes do not alter the frozen receipt", () => { const s=confirm(createFixture(),"fixed",20); const snap={before:s.attempt?.receiptBefore,after:s.attempt?.receiptAfter,target:s.attempt?.receiptTarget}; const later={...s,contributions:[...s.contributions,{id:"later",attemptId:"later",memberId:"jordan",communityId:"oak",goalId:"oak-500",amount:99,at:Date.now(),source:"demo" as const}]}; expect(goalTotal(later,"oak-500")).toBe(360); expect({before:later.attempt?.receiptBefore,after:later.attempt?.receiptAfter,target:later.attempt?.receiptTarget}).toEqual(snap); });
  it("legacy confirmed receipts without shared snapshots remain honestly partial", () => { const s=createFixture(); const old={...s,attempt:{id:"old",communityId:"oak",goalId:"oak-500",amount:10,stage:"confirmed" as const,lost:false,submittedAt:1,ownBefore:25}}; expect(old.attempt.receiptAfter).toBeUndefined(); expect(togetherOutcome(false,null,null,null,false).headline).toBe("Your contribution is recorded."); });
  it("share preview is unavailable without a complete valid shared snapshot", () => { const base: TogetherResult={amount:10,movement:"squats",communityName:"Oak Grove Together",goalTitle:"500 squats together",before:null,after:null,target:null,fresh:false,crossed:false}; expect(hasShareableSnapshot(base)).toBe(false); expect(hasShareableSnapshot({...base,before:241,after:261,target:500})).toBe(true); });
});